use std::collections::HashMap;
use std::sync::{Arc, Mutex};
use crate::core::{Vertex, Edge, Value, Tag, NullType};
use crate::storage::{StorageEngine, StorageError};
use thiserror::Error;

pub mod context;
pub mod visitor;
pub mod validator;
pub mod planner;
pub mod optimizer;
pub mod executor;
pub mod scheduler;
pub mod parser;

#[derive(Error, Debug, Clone)]
pub enum QueryError {
    #[error("Storage error: {0}")]
    StorageError(#[from] StorageError),
    #[error("Parse error: {0}")]
    ParseError(String),
    #[error("Invalid query: {0}")]
    InvalidQuery(String),
    #[error("Execution error: {0}")]
    ExecutionError(String),
    #[error("Expression error: {0}")]
    ExpressionError(String),
}

#[derive(Debug, Clone)]
pub enum Query {
    CreateNode {
        id: Option<Value>,
        tags: Vec<Tag>,
    },
    CreateEdge {
        src: Value,
        dst: Value,
        edge_type: String,
        name: String,
        ranking: i64,
        properties: HashMap<String, Value>,
    },
    MatchNodes {
        tags: Option<Vec<String>>,  // Filter by tag names
        conditions: Vec<Condition>,
    },
    DeleteNode {
        id: Value,
    },
    UpdateNode {
        id: Value,
        tags: Vec<Tag>,
    },
}

#[derive(Debug, Clone)]
pub enum Condition {
    PropertyEquals(String, Value),
    PropertyGreaterThan(String, Value),
    PropertyLessThan(String, Value),
    PropertyIn(String, Vec<Value>),
}

#[derive(Debug)]
pub enum QueryResult {
    NodeId(Value),
    EdgeId(Value),
    Nodes(Vec<Vertex>),
    Edges(Vec<Edge>),
    Count(usize),
    Success,
}

pub struct QueryExecutor<S: StorageEngine> {
    storage: Arc<Mutex<S>>,
}

impl<S: StorageEngine> std::fmt::Debug for QueryExecutor<S> {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("QueryExecutor")
            .field("storage", &"<Arc<Mutex<StorageEngine>>")
            .finish()
    }
}

impl<S: StorageEngine> QueryExecutor<S> {
    pub fn new(storage: Arc<Mutex<S>>) -> Self {
        Self { storage }
    }

    pub fn execute(&mut self, query: Query) -> Result<QueryResult, QueryError> {
        match query {
            Query::CreateNode { id: node_id, tags } => {
                let mut storage = self.storage.lock().unwrap();
                let vertex = if let Some(id) = node_id {
                    Vertex::new(id, tags)
                } else {
                    Vertex::new(Value::Null(NullType::Null), tags)  // ID will be generated by storage
                };
                let id = storage.insert_node(vertex)?;
                Ok(QueryResult::NodeId(id))
            }
            Query::CreateEdge { src, dst, edge_type, name: _, ranking, properties } => {
                // Verify that both nodes exist before creating an edge
                {
                    let storage = self.storage.lock().unwrap();
                    if storage.get_node(&src)?.is_none() {
                        return Err(QueryError::InvalidQuery(format!("Source node {:?} does not exist", src)));
                    }
                    if storage.get_node(&dst)?.is_none() {
                        return Err(QueryError::InvalidQuery(format!("Target node {:?} does not exist", dst)));
                    }
                }

                let mut storage = self.storage.lock().unwrap();
                let edge = Edge::new(src, dst, edge_type, ranking, properties);
                storage.insert_edge(edge)?;
                Ok(QueryResult::Success) // No ID returned for edge in our new model
            }
            Query::MatchNodes { tags, conditions } => {
                // Improved implementation - in a real system, this would utilize indexes
                // For now we implement a basic property-based filter
                let all_nodes = self.get_all_nodes()?;

                let filtered_nodes = all_nodes.into_iter()
                    .filter(|node| {
                        // Check tags if specified
                        if let Some(ref req_tags) = tags {
                            if !req_tags.iter().all(|tag_name|
                                node.tags.iter().any(|tag| tag.name == *tag_name)
                            ) {
                                return false;
                            }
                        }

                        // Check conditions if specified
                        for condition in &conditions {
                            if !self.check_condition(node, condition) {
                                return false;
                            }
                        }

                        true
                    })
                    .collect();

                Ok(QueryResult::Nodes(filtered_nodes))
            }
            Query::DeleteNode { id } => {
                let mut storage = self.storage.lock().unwrap();
                storage.delete_node(&id)?;
                Ok(QueryResult::Success)
            }
            Query::UpdateNode { id, tags } => {
                let mut storage = self.storage.lock().unwrap();
                if let Some(mut existing_vertex) = storage.get_node(&id)? {
                    // Add new tags to the existing vertex
                    for tag in tags {
                        existing_vertex.add_tag(tag);
                    }
                    storage.update_node(existing_vertex)?;
                    Ok(QueryResult::Success)
                } else {
                    Err(QueryError::InvalidQuery(format!("Node {:?} not found", id)))
                }
            }
        }
    }

    // Helper function to get all nodes (in a real implementation this might use indexes)
    fn get_all_nodes(&mut self) -> Result<Vec<Vertex>, QueryError> {
        // This is a simplified implementation
        // In a real system, you might maintain an index of all node IDs
        // or implement a scan operation on the storage layer
        Ok(Vec::new()) // Placeholder - in a real implementation, we'd scan all nodes
    }

    // Helper function to check if a node matches a condition
    fn check_condition(&self, vertex: &Vertex, condition: &Condition) -> bool {
        match condition {
            Condition::PropertyEquals(key, expected_value) => {
                // Look for the property in any of the vertex's tags
                for tag in &vertex.tags {
                    if let Some(actual_value) = tag.properties.get(key) {
                        if actual_value == expected_value {
                            return true;
                        }
                    }
                }
                false
            }
            Condition::PropertyGreaterThan(key, expected_value) => {
                // Look for the property in any of the vertex's tags
                for tag in &vertex.tags {
                    if let Some(actual_value) = tag.properties.get(key) {
                        match (actual_value, expected_value) {
                            (Value::Int(a), Value::Int(b)) => return a > b,
                            (Value::Float(a), Value::Float(b)) => return a > b,
                            _ => continue, // Skip if types don't match
                        }
                    }
                }
                false
            }
            Condition::PropertyLessThan(key, expected_value) => {
                // Look for the property in any of the vertex's tags
                for tag in &vertex.tags {
                    if let Some(actual_value) = tag.properties.get(key) {
                        match (actual_value, expected_value) {
                            (Value::Int(a), Value::Int(b)) => return a < b,
                            (Value::Float(a), Value::Float(b)) => return a < b,
                            _ => continue, // Skip if types don't match
                        }
                    }
                }
                false
            }
            Condition::PropertyIn(key, valid_values) => {
                // Look for the property in any of the vertex's tags
                for tag in &vertex.tags {
                    if let Some(actual_value) = tag.properties.get(key) {
                        if valid_values.contains(actual_value) {
                            return true;
                        }
                    }
                }
                false
            }
        }
    }
}

use crate::query::parser::parser::parser::{Parser as NewParser};
use crate::query::parser::ast::ast::{Statement, Expression as AstExpression};

pub struct QueryParser;

impl QueryParser {
    pub fn parse(&self, query_string: &str) -> Result<Query, QueryError> {
        // Use the new parser implementation
        let mut parser = NewParser::new(query_string);
        let statements = parser.parse()
            .map_err(|e| QueryError::ParseError(e.to_string()))?;

        if statements.is_empty() {
            return Err(QueryError::ParseError("No valid statement found".to_string()));
        }

        // Convert the first statement to our Query type
        // For now, we'll handle only simple cases and extend as needed
        match &statements[0] {
            crate::query::parser::ast::ast::Statement::Match(match_stmt) => self.convert_match_statement(&match_stmt),
            crate::query::parser::ast::ast::Statement::CreateNode(create_node_stmt) => self.convert_create_node_statement(&create_node_stmt),
            crate::query::parser::ast::ast::Statement::CreateEdge(create_edge_stmt) => self.convert_create_edge_statement(&create_edge_stmt),
            crate::query::parser::ast::ast::Statement::Delete(delete_stmt) => self.convert_delete_statement(&delete_stmt),
            crate::query::parser::ast::ast::Statement::Update(update_stmt) => self.convert_update_statement(&update_stmt),
            // Add more statement types as needed
            _ => Err(QueryError::ParseError(format!("Unsupported statement type: {:?}", statements[0])))
        }
    }

    fn convert_match_statement(
        &self,
        match_stmt: &crate::query::parser::ast::ast::MatchStatement,
    ) -> Result<Query, QueryError> {
        use crate::query::parser::ast::ast::{MatchClause, MatchPathSegment};

        // For now, we'll implement a basic conversion
        // We'll extract WHERE conditions and any specified tags

        let mut tags = None;
        let mut conditions = Vec::new();

        // Process clauses to extract tags and conditions
        for clause in &match_stmt.clauses {
            match clause {
                MatchClause::Match(match_detail) => {
                    // Extract tag information from patterns
                    for path in &match_detail.patterns {
                        for segment in &path.path {
                            if let MatchPathSegment::Node(node) = segment {
                                if !node.labels.is_empty() {
                                    let tag_names: Vec<String> = node.labels.iter()
                                        .map(|label| label.name.clone())
                                        .collect();
                                    tags = Some(tag_names);
                                }
                            }
                        }
                    }

                    // Process WHERE clause
                    if let Some(where_clause) = &match_detail.where_clause {
                        if let Ok(condition) = self.convert_expression(&where_clause.condition) {
                            conditions.push(condition);
                        }
                    }
                }
                MatchClause::Where(where_clause) => {
                    if let Ok(condition) = self.convert_expression(&where_clause.condition) {
                        conditions.push(condition);
                    }
                }
                _ => {} // Other clauses are handled at a higher level or ignored for now
            }
        }

        Ok(Query::MatchNodes {
            tags,
            conditions,
        })
    }

    fn convert_create_node_statement(
        &self,
        create_node_stmt: &crate::query::parser::ast::ast::CreateNodeStatement,
    ) -> Result<Query, QueryError> {
        use crate::query::parser::ast::ast::TagIdentifier;

        // Convert tags
        let tags: Vec<Tag> = create_node_stmt.tags.iter()
            .map(|tag_id: &TagIdentifier| {
                let properties = match &tag_id.properties {
                    Some(props) => {
                        let mut map = HashMap::new();
                        for (key, value_expr) in props {
                            if let Ok(value) = self.convert_ast_expression_to_value(value_expr) {
                                map.insert(key.clone(), value);
                            }
                        }
                        map
                    },
                    None => HashMap::new(),
                };

                Tag::new(tag_id.name.clone(), properties)
            })
            .collect();

        Ok(Query::CreateNode {
            id: None, // ID will be generated
            tags,
        })
    }

    fn convert_create_edge_statement(
        &self,
        create_edge_stmt: &crate::query::parser::ast::ast::CreateEdgeStatement,
    ) -> Result<Query, QueryError> {
        // Convert source and destination expressions to values
        let src = self.convert_ast_expression_to_value(&create_edge_stmt.src)?;
        let dst = self.convert_ast_expression_to_value(&create_edge_stmt.dst)?;

        // Convert properties
        let mut properties = HashMap::new();
        for prop in &create_edge_stmt.properties {
            let value = self.convert_ast_expression_to_value(&prop.value)?;
            properties.insert(prop.name.clone(), value);
        }

        Ok(Query::CreateEdge {
            src,
            dst,
            edge_type: create_edge_stmt.edge_type.clone(),
            name: String::new(), // Not used in our model
            ranking: 0, // Default ranking
            properties,
        })
    }

    fn convert_delete_statement(
        &self,
        delete_stmt: &crate::query::parser::ast::ast::DeleteStatement,
    ) -> Result<Query, QueryError> {
        if !delete_stmt.delete_vertices {
            return Err(QueryError::ParseError("Deleting edges not supported in this model".to_string()));
        }

        if delete_stmt.vertex_exprs.is_empty() {
            return Err(QueryError::ParseError("No vertex specified for deletion".to_string()));
        }

        // For now, we'll use the first vertex expression as the ID
        let id = self.convert_ast_expression_to_value(&delete_stmt.vertex_exprs[0])?;

        Ok(Query::DeleteNode { id })
    }

    fn convert_update_statement(
        &self,
        update_stmt: &crate::query::parser::ast::ast::UpdateStatement,
    ) -> Result<Query, QueryError> {
        use crate::query::parser::ast::ast::PropertyRef;

        if !update_stmt.update_vertices {
            return Err(QueryError::ParseError("Updating edges not supported in this model".to_string()));
        }

        let id = if let Some(ref vertex_ref) = update_stmt.vertex_ref {
            self.convert_ast_expression_to_value(vertex_ref)?
        } else {
            return Err(QueryError::ParseError("No vertex specified for update".to_string()));
        };

        // Convert update items to tags
        let mut tags = Vec::new();
        for assignment in &update_stmt.update_items {
            match &assignment.prop {
                PropertyRef::InlineProp(prop_name) => {
                    // For now, we'll create a default tag with the updated properties
                    let value = self.convert_ast_expression_to_value(&assignment.value)?;
                    let mut properties = HashMap::new();
                    properties.insert(prop_name.clone(), value);
                    tags.push(Tag::new("UpdatedTag".to_string(), properties));
                }
                PropertyRef::Prop(tag_name, prop_name) => {
                    let value = self.convert_ast_expression_to_value(&assignment.value)?;
                    let mut properties = HashMap::new();
                    properties.insert(prop_name.clone(), value);
                    tags.push(Tag::new(tag_name.clone(), properties));
                }
            }
        }

        Ok(Query::UpdateNode { id, tags })
    }

    fn convert_expression(
        &self,
        expr: &crate::query::parser::ast::ast::Expression,
    ) -> Result<Condition, QueryError> {
        use crate::query::parser::ast::ast::{Expression, RelationalOp};

        // Convert AST expression to our Condition type
        // This is a simplified implementation
        match expr {
            Expression::Relational(left, op, right) => {
                // Convert left and right expressions to property names and values
                let prop_name = self.extract_property_name(left)?;
                let value = self.convert_ast_expression_to_value(right)?;

                match op {
                    RelationalOp::Eq => Ok(Condition::PropertyEquals(prop_name, value)),
                    RelationalOp::Ne => Err(QueryError::ParseError("Not equal operator not supported yet".to_string())),
                    RelationalOp::Lt => Ok(Condition::PropertyLessThan(prop_name, value)),
                    RelationalOp::Le => Err(QueryError::ParseError("Less than or equal operator not supported yet".to_string())),
                    RelationalOp::Gt => Ok(Condition::PropertyGreaterThan(prop_name, value)),
                    RelationalOp::Ge => Err(QueryError::ParseError("Greater than or equal operator not supported yet".to_string())),
                    RelationalOp::Regex => Err(QueryError::ParseError("Regex operator not supported yet".to_string())),
                }
            }
            _ => Err(QueryError::ParseError("Unsupported expression type for condition".to_string())),
        }
    }

    fn extract_property_name(&self, expr: &crate::query::parser::ast::ast::Expression) -> Result<String, QueryError> {
        use crate::query::parser::ast::ast::Expression;

        // Extract the property name from an expression
        match expr {
            Expression::PropertyAccess(_, prop_name) => Ok(prop_name.clone()),
            Expression::Variable(name) => Ok(name.clone()),
            _ => Err(QueryError::ParseError("Could not extract property name from expression".to_string())),
        }
    }

    fn convert_ast_expression_to_value(
        &self,
        expr: &crate::query::parser::ast::ast::Expression,
    ) -> Result<Value, QueryError> {
        use crate::query::parser::ast::ast::Expression;

        // Convert an AST expression to a Value
        match expr {
            Expression::Constant(value) => Ok(value.clone()),
            Expression::Variable(name) => {
                // In a real implementation, this would look up the variable in the execution context
                // For now, we'll return a string representation
                Ok(Value::String(name.clone()))
            }
            Expression::FunctionCall(func) => {
                // Function calls would need to be evaluated in the execution context
                Err(QueryError::ParseError("Function calls in expressions not supported in parsing".to_string()))
            }
            _ => Err(QueryError::ParseError("Unsupported expression type for value conversion".to_string())),
        }
    }
}