use std::collections::HashMap;
use std::sync::{Arc, Mutex};
use crate::core::{Vertex, Edge, Value, Tag, NullType};
use crate::storage::{StorageEngine, StorageError};
use thiserror::Error;

pub mod context;
pub mod visitor;
pub mod validator;
pub mod planner;
pub mod optimizer;
pub mod executor;
pub mod scheduler;

#[derive(Error, Debug, Clone)]
pub enum QueryError {
    #[error("Storage error: {0}")]
    StorageError(#[from] StorageError),
    #[error("Parse error: {0}")]
    ParseError(String),
    #[error("Invalid query: {0}")]
    InvalidQuery(String),
    #[error("Execution error: {0}")]
    ExecutionError(String),
    #[error("Expression error: {0}")]
    ExpressionError(String),
}

#[derive(Debug, Clone)]
pub enum Query {
    CreateNode {
        id: Option<Value>,
        tags: Vec<Tag>,
    },
    CreateEdge {
        src: Value,
        dst: Value,
        edge_type: String,
        name: String,
        ranking: i64,
        properties: HashMap<String, Value>,
    },
    MatchNodes {
        tags: Option<Vec<String>>,  // Filter by tag names
        conditions: Vec<Condition>,
    },
    DeleteNode {
        id: Value,
    },
    UpdateNode {
        id: Value,
        tags: Vec<Tag>,
    },
}

#[derive(Debug, Clone)]
pub enum Condition {
    PropertyEquals(String, Value),
    PropertyGreaterThan(String, Value),
    PropertyLessThan(String, Value),
    PropertyIn(String, Vec<Value>),
}

#[derive(Debug)]
pub enum QueryResult {
    NodeId(Value),
    EdgeId(Value),
    Nodes(Vec<Vertex>),
    Edges(Vec<Edge>),
    Count(usize),
    Success,
}

pub struct QueryExecutor<S: StorageEngine> {
    storage: Arc<Mutex<S>>,
}

impl<S: StorageEngine> std::fmt::Debug for QueryExecutor<S> {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("QueryExecutor")
            .field("storage", &"<Arc<Mutex<StorageEngine>>")
            .finish()
    }
}

impl<S: StorageEngine> QueryExecutor<S> {
    pub fn new(storage: Arc<Mutex<S>>) -> Self {
        Self { storage }
    }

    pub fn execute(&mut self, query: Query) -> Result<QueryResult, QueryError> {
        match query {
            Query::CreateNode { id: node_id, tags } => {
                let mut storage = self.storage.lock().unwrap();
                let vertex = if let Some(id) = node_id {
                    Vertex::new(id, tags)
                } else {
                    Vertex::new(Value::Null(NullType::Null), tags)  // ID will be generated by storage
                };
                let id = storage.insert_node(vertex)?;
                Ok(QueryResult::NodeId(id))
            }
            Query::CreateEdge { src, dst, edge_type, name: _, ranking, properties } => {
                // Verify that both nodes exist before creating an edge
                {
                    let storage = self.storage.lock().unwrap();
                    if storage.get_node(&src)?.is_none() {
                        return Err(QueryError::InvalidQuery(format!("Source node {:?} does not exist", src)));
                    }
                    if storage.get_node(&dst)?.is_none() {
                        return Err(QueryError::InvalidQuery(format!("Target node {:?} does not exist", dst)));
                    }
                }

                let mut storage = self.storage.lock().unwrap();
                let edge = Edge::new(src, dst, edge_type, ranking, properties);
                storage.insert_edge(edge)?;
                Ok(QueryResult::Success) // No ID returned for edge in our new model
            }
            Query::MatchNodes { tags, conditions } => {
                // Improved implementation - in a real system, this would utilize indexes
                // For now we implement a basic property-based filter
                let all_nodes = self.get_all_nodes()?;

                let filtered_nodes = all_nodes.into_iter()
                    .filter(|node| {
                        // Check tags if specified
                        if let Some(ref req_tags) = tags {
                            if !req_tags.iter().all(|tag_name|
                                node.tags.iter().any(|tag| tag.name == *tag_name)
                            ) {
                                return false;
                            }
                        }

                        // Check conditions if specified
                        for condition in &conditions {
                            if !self.check_condition(node, condition) {
                                return false;
                            }
                        }

                        true
                    })
                    .collect();

                Ok(QueryResult::Nodes(filtered_nodes))
            }
            Query::DeleteNode { id } => {
                let mut storage = self.storage.lock().unwrap();
                storage.delete_node(&id)?;
                Ok(QueryResult::Success)
            }
            Query::UpdateNode { id, tags } => {
                let mut storage = self.storage.lock().unwrap();
                if let Some(mut existing_vertex) = storage.get_node(&id)? {
                    // Add new tags to the existing vertex
                    for tag in tags {
                        existing_vertex.add_tag(tag);
                    }
                    storage.update_node(existing_vertex)?;
                    Ok(QueryResult::Success)
                } else {
                    Err(QueryError::InvalidQuery(format!("Node {:?} not found", id)))
                }
            }
        }
    }

    // Helper function to get all nodes (in a real implementation this might use indexes)
    fn get_all_nodes(&mut self) -> Result<Vec<Vertex>, QueryError> {
        // This is a simplified implementation
        // In a real system, you might maintain an index of all node IDs
        // or implement a scan operation on the storage layer
        Ok(Vec::new()) // Placeholder - in a real implementation, we'd scan all nodes
    }

    // Helper function to check if a node matches a condition
    fn check_condition(&self, vertex: &Vertex, condition: &Condition) -> bool {
        match condition {
            Condition::PropertyEquals(key, expected_value) => {
                // Look for the property in any of the vertex's tags
                for tag in &vertex.tags {
                    if let Some(actual_value) = tag.properties.get(key) {
                        if actual_value == expected_value {
                            return true;
                        }
                    }
                }
                false
            }
            Condition::PropertyGreaterThan(key, expected_value) => {
                // Look for the property in any of the vertex's tags
                for tag in &vertex.tags {
                    if let Some(actual_value) = tag.properties.get(key) {
                        match (actual_value, expected_value) {
                            (Value::Int(a), Value::Int(b)) => return a > b,
                            (Value::Float(a), Value::Float(b)) => return a > b,
                            _ => continue, // Skip if types don't match
                        }
                    }
                }
                false
            }
            Condition::PropertyLessThan(key, expected_value) => {
                // Look for the property in any of the vertex's tags
                for tag in &vertex.tags {
                    if let Some(actual_value) = tag.properties.get(key) {
                        match (actual_value, expected_value) {
                            (Value::Int(a), Value::Int(b)) => return a < b,
                            (Value::Float(a), Value::Float(b)) => return a < b,
                            _ => continue, // Skip if types don't match
                        }
                    }
                }
                false
            }
            Condition::PropertyIn(key, valid_values) => {
                // Look for the property in any of the vertex's tags
                for tag in &vertex.tags {
                    if let Some(actual_value) = tag.properties.get(key) {
                        if valid_values.contains(actual_value) {
                            return true;
                        }
                    }
                }
                false
            }
        }
    }
}

pub struct QueryParser;

impl QueryParser {
    pub fn parse(&self, query_string: &str) -> Result<Query, QueryError> {
        // Simplified parser for demonstration
        // A real implementation would have a proper parser

        let lower_query = query_string.trim().to_uppercase();

        if lower_query.starts_with("CREATE NODE") {
            // Parse CREATE NODE query
            // This is a simplified example - real parsing would be more robust
            Ok(Query::CreateNode {
                id: None,
                tags: vec![Tag::new("Default".to_string(), HashMap::new())],
            })
        } else if lower_query.starts_with("MATCH") {
            // Parse MATCH query
            Ok(Query::MatchNodes {
                tags: None,
                conditions: Vec::new(),
            })
        } else {
            Err(QueryError::ParseError("Unsupported query type".to_string()))
        }
    }
}