//! 执行器枚举定义
//!
//! 使用静态分发替代动态分发，所有执行器类型都包含在此枚举中
//! 通过为枚举实现 Executor trait，可以统一处理所有执行器类型

use async_trait::async_trait;

use std::fmt;

use std::fmt::{Debug, Formatter};
use std::sync::{Arc, Mutex};
use std::time::Instant;

use crate::storage::StorageEngine;

use super::admin::{
    AlterEdgeExecutor, AlterTagExecutor, ChangePasswordExecutor, CreateEdgeExecutor,
    CreateSpaceExecutor, CreateTagExecutor, DescEdgeExecutor, DescSpaceExecutor, DescTagExecutor,
    DropEdgeExecutor, DropSpaceExecutor, DropTagExecutor, InsertEdgeExecutor, InsertVertexExecutor,
    UpdateExecutor,
};

use super::base::{BaseExecutor, ExecutorStats, StartExecutor, ExecutionContext, ExecutionResult, DBResult, Executor, InputExecutor};
use super::data_access::{
    AllPathsExecutor, GetNeighborsExecutor, GetPropExecutor, GetVerticesExecutor,
};
use super::data_processing::graph_traversal::{
    ExpandAllExecutor, ExpandExecutor, MultiShortestPathExecutor, ShortestPathExecutor,
    TraverseExecutor,
};
use super::data_processing::join::{CrossJoinExecutor, HashInnerJoinExecutor, HashLeftJoinExecutor, InnerJoinExecutor, LeftJoinExecutor};
use super::data_processing::set_operations::{IntersectExecutor, MinusExecutor, UnionAllExecutor, UnionExecutor};
use super::logic::{ForLoopExecutor, LoopExecutor, WhileLoopExecutor};
use super::result_processing::{
    AggregateExecutor, DedupExecutor, FilterExecutor, GroupByExecutor, HavingExecutor,
    LimitExecutor, ProjectExecutor, SampleExecutor, SortExecutor, TopNExecutor,
};
use super::result_processing::transformations::{
    AppendVerticesExecutor, AssignExecutor, PatternApplyExecutor, RollUpApplyExecutor, UnwindExecutor,
};

pub enum ExecutorEnum<S: StorageEngine + Send + 'static> {
    Start(StartExecutor<S>),
    Base(BaseExecutor<S>),
    GetVertices(GetVerticesExecutor<S>),
    GetNeighbors(GetNeighborsExecutor<S>),
    GetProp(GetPropExecutor<S>),
    AllPaths(AllPathsExecutor<S>),
    Expand(ExpandExecutor<S>),
    ExpandAll(ExpandAllExecutor<S>),
    Traverse(TraverseExecutor<S>),
    ShortestPath(ShortestPathExecutor<S>),
    MultiShortestPath(MultiShortestPathExecutor<S>),
    InnerJoin(InnerJoinExecutor<S>),
    HashInnerJoin(HashInnerJoinExecutor<S>),
    LeftJoin(LeftJoinExecutor<S>),
    HashLeftJoin(HashLeftJoinExecutor<S>),
    CrossJoin(CrossJoinExecutor<S>),
    Union(UnionExecutor<S>),
    UnionAll(UnionAllExecutor<S>),
    Minus(MinusExecutor<S>),
    Intersect(IntersectExecutor<S>),
    Filter(FilterExecutor<S>),
    Project(ProjectExecutor<S>),
    Limit(LimitExecutor<S>),
    Sort(SortExecutor<S>),
    TopN(TopNExecutor<S>),
    Sample(SampleExecutor<S>),
    Aggregate(AggregateExecutor<S>),
    GroupBy(GroupByExecutor<S>),
    Having(HavingExecutor<S>),
    Dedup(DedupExecutor<S>),
    Unwind(UnwindExecutor<S>),
    Assign(AssignExecutor<S>),
    AppendVertices(AppendVerticesExecutor<S>),
    RollUpApply(RollUpApplyExecutor<S>),
    PatternApply(PatternApplyExecutor<S>),
    Loop(LoopExecutor<S>),
    ForLoop(ForLoopExecutor<S>),
    WhileLoop(WhileLoopExecutor<S>),
    CreateSpace(CreateSpaceExecutor<S>),
    DropSpace(DropSpaceExecutor<S>),
    DescSpace(DescSpaceExecutor<S>),
    CreateTag(CreateTagExecutor<S>),
    AlterTag(AlterTagExecutor<S>),
    DescTag(DescTagExecutor<S>),
    DropTag(DropTagExecutor<S>),
    CreateEdge(CreateEdgeExecutor<S>),
    AlterEdge(AlterEdgeExecutor<S>),
    DescEdge(DescEdgeExecutor<S>),
    DropEdge(DropEdgeExecutor<S>),
    InsertVertex(InsertVertexExecutor<S>),
    InsertEdge(InsertEdgeExecutor<S>),
    Update(UpdateExecutor<S>),
    ChangePassword(ChangePasswordExecutor<S>),
}

impl<S: StorageEngine + Send + 'static> Debug for ExecutorEnum<S> {
    fn fmt(&self, f: &mut Formatter<'_>) -> fmt::Result {
        match self {
            ExecutorEnum::Start(exec) => f.write_str(&format!("ExecutorEnum::Start({})", exec.name())),
            ExecutorEnum::Base(exec) => f.write_str(&format!("ExecutorEnum::Base({})", exec.name())),
            ExecutorEnum::GetVertices(exec) => f.write_str(&format!("ExecutorEnum::GetVertices({})", exec.name())),
            ExecutorEnum::GetNeighbors(exec) => f.write_str(&format!("ExecutorEnum::GetNeighbors({})", exec.name())),
            ExecutorEnum::GetProp(exec) => f.write_str(&format!("ExecutorEnum::GetProp({})", exec.name())),
            ExecutorEnum::AllPaths(exec) => f.write_str(&format!("ExecutorEnum::AllPaths({})", exec.name())),
            ExecutorEnum::Expand(exec) => f.write_str(&format!("ExecutorEnum::Expand({})", exec.name())),
            ExecutorEnum::ExpandAll(exec) => f.write_str(&format!("ExecutorEnum::ExpandAll({})", exec.name())),
            ExecutorEnum::Traverse(exec) => f.write_str(&format!("ExecutorEnum::Traverse({})", exec.name())),
            ExecutorEnum::ShortestPath(exec) => f.write_str(&format!("ExecutorEnum::ShortestPath({})", exec.name())),
            ExecutorEnum::MultiShortestPath(exec) => f.write_str(&format!("ExecutorEnum::MultiShortestPath({})", exec.name())),
            ExecutorEnum::InnerJoin(exec) => f.write_str(&format!("ExecutorEnum::InnerJoin({})", exec.name())),
            ExecutorEnum::HashInnerJoin(exec) => f.write_str(&format!("ExecutorEnum::HashInnerJoin({})", exec.name())),
            ExecutorEnum::LeftJoin(exec) => f.write_str(&format!("ExecutorEnum::LeftJoin({})", exec.name())),
            ExecutorEnum::HashLeftJoin(exec) => f.write_str(&format!("ExecutorEnum::HashLeftJoin({})", exec.name())),
            ExecutorEnum::CrossJoin(exec) => f.write_str(&format!("ExecutorEnum::CrossJoin({})", exec.name())),
            ExecutorEnum::Union(exec) => f.write_str(&format!("ExecutorEnum::Union({})", exec.name())),
            ExecutorEnum::UnionAll(exec) => f.write_str(&format!("ExecutorEnum::UnionAll({})", exec.name())),
            ExecutorEnum::Minus(exec) => f.write_str(&format!("ExecutorEnum::Minus({})", exec.name())),
            ExecutorEnum::Intersect(exec) => f.write_str(&format!("ExecutorEnum::Intersect({})", exec.name())),
            ExecutorEnum::Filter(exec) => f.write_str(&format!("ExecutorEnum::Filter({})", exec.name())),
            ExecutorEnum::Project(exec) => f.write_str(&format!("ExecutorEnum::Project({})", exec.name())),
            ExecutorEnum::Limit(exec) => f.write_str(&format!("ExecutorEnum::Limit({})", exec.name())),
            ExecutorEnum::Sort(exec) => f.write_str(&format!("ExecutorEnum::Sort({})", exec.name())),
            ExecutorEnum::TopN(exec) => f.write_str(&format!("ExecutorEnum::TopN({})", exec.name())),
            ExecutorEnum::Sample(exec) => f.write_str(&format!("ExecutorEnum::Sample({})", exec.name())),
            ExecutorEnum::Aggregate(exec) => f.write_str(&format!("ExecutorEnum::Aggregate({})", exec.name())),
            ExecutorEnum::GroupBy(exec) => f.write_str(&format!("ExecutorEnum::GroupBy({})", exec.name())),
            ExecutorEnum::Having(exec) => f.write_str(&format!("ExecutorEnum::Having({})", exec.name())),
            ExecutorEnum::Dedup(exec) => f.write_str(&format!("ExecutorEnum::Dedup({})", exec.name())),
            ExecutorEnum::Unwind(exec) => f.write_str(&format!("ExecutorEnum::Unwind({})", exec.name())),
            ExecutorEnum::Assign(exec) => f.write_str(&format!("ExecutorEnum::Assign({})", exec.name())),
            ExecutorEnum::AppendVertices(exec) => f.write_str(&format!("ExecutorEnum::AppendVertices({})", exec.name())),
            ExecutorEnum::RollUpApply(exec) => f.write_str(&format!("ExecutorEnum::RollUpApply({})", exec.name())),
            ExecutorEnum::PatternApply(exec) => f.write_str(&format!("ExecutorEnum::PatternApply({})", exec.name())),
            ExecutorEnum::Loop(exec) => f.write_str(&format!("ExecutorEnum::Loop({})", exec.name())),
            ExecutorEnum::ForLoop(exec) => f.write_str(&format!("ExecutorEnum::ForLoop({})", exec.name())),
            ExecutorEnum::WhileLoop(exec) => f.write_str(&format!("ExecutorEnum::WhileLoop({})", exec.name())),
            ExecutorEnum::CreateSpace(exec) => f.write_str(&format!("ExecutorEnum::CreateSpace({})", exec.name())),
            ExecutorEnum::DropSpace(exec) => f.write_str(&format!("ExecutorEnum::DropSpace({})", exec.name())),
            ExecutorEnum::DescSpace(exec) => f.write_str(&format!("ExecutorEnum::DescSpace({})", exec.name())),
            ExecutorEnum::CreateTag(exec) => f.write_str(&format!("ExecutorEnum::CreateTag({})", exec.name())),
            ExecutorEnum::AlterTag(exec) => f.write_str(&format!("ExecutorEnum::AlterTag({})", exec.name())),
            ExecutorEnum::DescTag(exec) => f.write_str(&format!("ExecutorEnum::DescTag({})", exec.name())),
            ExecutorEnum::DropTag(exec) => f.write_str(&format!("ExecutorEnum::DropTag({})", exec.name())),
            ExecutorEnum::CreateEdge(exec) => f.write_str(&format!("ExecutorEnum::CreateEdge({})", exec.name())),
            ExecutorEnum::AlterEdge(exec) => f.write_str(&format!("ExecutorEnum::AlterEdge({})", exec.name())),
            ExecutorEnum::DescEdge(exec) => f.write_str(&format!("ExecutorEnum::DescEdge({})", exec.name())),
            ExecutorEnum::DropEdge(exec) => f.write_str(&format!("ExecutorEnum::DropEdge({})", exec.name())),
            ExecutorEnum::InsertVertex(exec) => f.write_str(&format!("ExecutorEnum::InsertVertex({})", exec.name())),
            ExecutorEnum::InsertEdge(exec) => f.write_str(&format!("ExecutorEnum::InsertEdge({})", exec.name())),
            ExecutorEnum::Update(exec) => f.write_str(&format!("ExecutorEnum::Update({})", exec.name())),
            ExecutorEnum::ChangePassword(exec) => f.write_str(&format!("ExecutorEnum::ChangePassword({})", exec.name())),
        }
    }
}

impl<S: StorageEngine + Send + 'static> ExecutorEnum<S> {
    pub fn id(&self) -> i64 {
        match self {
            ExecutorEnum::Start(exec) => exec.id(),
            ExecutorEnum::Base(exec) => exec.id(),
            ExecutorEnum::GetVertices(exec) => exec.id(),
            ExecutorEnum::GetNeighbors(exec) => exec.id(),
            ExecutorEnum::GetProp(exec) => exec.id(),
            ExecutorEnum::AllPaths(exec) => exec.id(),
            ExecutorEnum::Expand(exec) => exec.id(),
            ExecutorEnum::ExpandAll(exec) => exec.id(),
            ExecutorEnum::Traverse(exec) => exec.id(),
            ExecutorEnum::ShortestPath(exec) => exec.id(),
            ExecutorEnum::MultiShortestPath(exec) => exec.id(),
            ExecutorEnum::InnerJoin(exec) => exec.id(),
            ExecutorEnum::HashInnerJoin(exec) => exec.id(),
            ExecutorEnum::LeftJoin(exec) => exec.id(),
            ExecutorEnum::HashLeftJoin(exec) => exec.id(),
            ExecutorEnum::CrossJoin(exec) => exec.id(),
            ExecutorEnum::Union(exec) => exec.id(),
            ExecutorEnum::UnionAll(exec) => exec.id(),
            ExecutorEnum::Minus(exec) => exec.id(),
            ExecutorEnum::Intersect(exec) => exec.id(),
            ExecutorEnum::Filter(exec) => exec.id(),
            ExecutorEnum::Project(exec) => exec.id(),
            ExecutorEnum::Limit(exec) => exec.id(),
            ExecutorEnum::Sort(exec) => exec.id(),
            ExecutorEnum::TopN(exec) => exec.id(),
            ExecutorEnum::Sample(exec) => exec.id(),
            ExecutorEnum::Aggregate(exec) => exec.id(),
            ExecutorEnum::GroupBy(exec) => exec.id(),
            ExecutorEnum::Having(exec) => exec.id(),
            ExecutorEnum::Dedup(exec) => exec.id(),
            ExecutorEnum::Unwind(exec) => exec.id(),
            ExecutorEnum::Assign(exec) => exec.id(),
            ExecutorEnum::AppendVertices(exec) => exec.id(),
            ExecutorEnum::RollUpApply(exec) => exec.id(),
            ExecutorEnum::PatternApply(exec) => exec.id(),
            ExecutorEnum::Loop(exec) => exec.id(),
            ExecutorEnum::ForLoop(exec) => exec.id(),
            ExecutorEnum::WhileLoop(exec) => exec.id(),
            ExecutorEnum::CreateSpace(exec) => exec.id(),
            ExecutorEnum::DropSpace(exec) => exec.id(),
            ExecutorEnum::DescSpace(exec) => exec.id(),
            ExecutorEnum::CreateTag(exec) => exec.id(),
            ExecutorEnum::AlterTag(exec) => exec.id(),
            ExecutorEnum::DescTag(exec) => exec.id(),
            ExecutorEnum::DropTag(exec) => exec.id(),
            ExecutorEnum::CreateEdge(exec) => exec.id(),
            ExecutorEnum::AlterEdge(exec) => exec.id(),
            ExecutorEnum::DescEdge(exec) => exec.id(),
            ExecutorEnum::DropEdge(exec) => exec.id(),
            ExecutorEnum::InsertVertex(exec) => exec.id(),
            ExecutorEnum::InsertEdge(exec) => exec.id(),
            ExecutorEnum::Update(exec) => exec.id(),
            ExecutorEnum::ChangePassword(exec) => exec.id(),
        }
    }

    pub fn name(&self) -> &str {
        match self {
            ExecutorEnum::Start(exec) => exec.name(),
            ExecutorEnum::Base(exec) => exec.name(),
            ExecutorEnum::GetVertices(exec) => exec.name(),
            ExecutorEnum::GetNeighbors(exec) => exec.name(),
            ExecutorEnum::GetProp(exec) => exec.name(),
            ExecutorEnum::AllPaths(exec) => exec.name(),
            ExecutorEnum::Expand(exec) => exec.name(),
            ExecutorEnum::ExpandAll(exec) => exec.name(),
            ExecutorEnum::Traverse(exec) => exec.name(),
            ExecutorEnum::ShortestPath(exec) => exec.name(),
            ExecutorEnum::MultiShortestPath(exec) => exec.name(),
            ExecutorEnum::InnerJoin(exec) => exec.name(),
            ExecutorEnum::HashInnerJoin(exec) => exec.name(),
            ExecutorEnum::LeftJoin(exec) => exec.name(),
            ExecutorEnum::HashLeftJoin(exec) => exec.name(),
            ExecutorEnum::CrossJoin(exec) => exec.name(),
            ExecutorEnum::Union(exec) => exec.name(),
            ExecutorEnum::UnionAll(exec) => exec.name(),
            ExecutorEnum::Minus(exec) => exec.name(),
            ExecutorEnum::Intersect(exec) => exec.name(),
            ExecutorEnum::Filter(exec) => exec.name(),
            ExecutorEnum::Project(exec) => exec.name(),
            ExecutorEnum::Limit(exec) => exec.name(),
            ExecutorEnum::Sort(exec) => exec.name(),
            ExecutorEnum::TopN(exec) => exec.name(),
            ExecutorEnum::Sample(exec) => exec.name(),
            ExecutorEnum::Aggregate(exec) => exec.name(),
            ExecutorEnum::GroupBy(exec) => exec.name(),
            ExecutorEnum::Having(exec) => exec.name(),
            ExecutorEnum::Dedup(exec) => exec.name(),
            ExecutorEnum::Unwind(exec) => exec.name(),
            ExecutorEnum::Assign(exec) => exec.name(),
            ExecutorEnum::AppendVertices(exec) => exec.name(),
            ExecutorEnum::RollUpApply(exec) => exec.name(),
            ExecutorEnum::PatternApply(exec) => exec.name(),
            ExecutorEnum::Loop(exec) => exec.name(),
            ExecutorEnum::ForLoop(exec) => exec.name(),
            ExecutorEnum::WhileLoop(exec) => exec.name(),
            ExecutorEnum::CreateSpace(exec) => exec.name(),
            ExecutorEnum::DropSpace(exec) => exec.name(),
            ExecutorEnum::DescSpace(exec) => exec.name(),
            ExecutorEnum::CreateTag(exec) => exec.name(),
            ExecutorEnum::AlterTag(exec) => exec.name(),
            ExecutorEnum::DescTag(exec) => exec.name(),
            ExecutorEnum::DropTag(exec) => exec.name(),
            ExecutorEnum::CreateEdge(exec) => exec.name(),
            ExecutorEnum::AlterEdge(exec) => exec.name(),
            ExecutorEnum::DescEdge(exec) => exec.name(),
            ExecutorEnum::DropEdge(exec) => exec.name(),
            ExecutorEnum::InsertVertex(exec) => exec.name(),
            ExecutorEnum::InsertEdge(exec) => exec.name(),
            ExecutorEnum::Update(exec) => exec.name(),
            ExecutorEnum::ChangePassword(exec) => exec.name(),
        }
    }

    pub fn stats(&self) -> &ExecutorStats {
        match self {
            ExecutorEnum::Start(exec) => exec.stats(),
            ExecutorEnum::Base(exec) => exec.stats(),
            ExecutorEnum::GetVertices(exec) => exec.stats(),
            ExecutorEnum::GetNeighbors(exec) => exec.stats(),
            ExecutorEnum::GetProp(exec) => exec.stats(),
            ExecutorEnum::AllPaths(exec) => exec.stats(),
            ExecutorEnum::Expand(exec) => exec.stats(),
            ExecutorEnum::ExpandAll(exec) => exec.stats(),
            ExecutorEnum::Traverse(exec) => exec.stats(),
            ExecutorEnum::ShortestPath(exec) => exec.stats(),
            ExecutorEnum::MultiShortestPath(exec) => exec.stats(),
            ExecutorEnum::InnerJoin(exec) => exec.stats(),
            ExecutorEnum::HashInnerJoin(exec) => exec.stats(),
            ExecutorEnum::LeftJoin(exec) => exec.stats(),
            ExecutorEnum::HashLeftJoin(exec) => exec.stats(),
            ExecutorEnum::CrossJoin(exec) => exec.stats(),
            ExecutorEnum::Union(exec) => exec.stats(),
            ExecutorEnum::UnionAll(exec) => exec.stats(),
            ExecutorEnum::Minus(exec) => exec.stats(),
            ExecutorEnum::Intersect(exec) => exec.stats(),
            ExecutorEnum::Filter(exec) => exec.stats(),
            ExecutorEnum::Project(exec) => exec.stats(),
            ExecutorEnum::Limit(exec) => exec.stats(),
            ExecutorEnum::Sort(exec) => exec.stats(),
            ExecutorEnum::TopN(exec) => exec.stats(),
            ExecutorEnum::Sample(exec) => exec.stats(),
            ExecutorEnum::Aggregate(exec) => exec.stats(),
            ExecutorEnum::GroupBy(exec) => exec.stats(),
            ExecutorEnum::Having(exec) => exec.stats(),
            ExecutorEnum::Dedup(exec) => exec.stats(),
            ExecutorEnum::Unwind(exec) => exec.stats(),
            ExecutorEnum::Assign(exec) => exec.stats(),
            ExecutorEnum::AppendVertices(exec) => exec.stats(),
            ExecutorEnum::RollUpApply(exec) => exec.stats(),
            ExecutorEnum::PatternApply(exec) => exec.stats(),
            ExecutorEnum::Loop(exec) => exec.stats(),
            ExecutorEnum::ForLoop(exec) => exec.stats(),
            ExecutorEnum::WhileLoop(exec) => exec.stats(),
            ExecutorEnum::CreateSpace(exec) => exec.stats(),
            ExecutorEnum::DropSpace(exec) => exec.stats(),
            ExecutorEnum::DescSpace(exec) => exec.stats(),
            ExecutorEnum::CreateTag(exec) => exec.stats(),
            ExecutorEnum::AlterTag(exec) => exec.stats(),
            ExecutorEnum::DescTag(exec) => exec.stats(),
            ExecutorEnum::DropTag(exec) => exec.stats(),
            ExecutorEnum::CreateEdge(exec) => exec.stats(),
            ExecutorEnum::AlterEdge(exec) => exec.stats(),
            ExecutorEnum::DescEdge(exec) => exec.stats(),
            ExecutorEnum::DropEdge(exec) => exec.stats(),
            ExecutorEnum::InsertVertex(exec) => exec.stats(),
            ExecutorEnum::InsertEdge(exec) => exec.stats(),
            ExecutorEnum::Update(exec) => exec.stats(),
            ExecutorEnum::ChangePassword(exec) => exec.stats(),
        }
    }

    pub fn stats_mut(&mut self) -> &mut ExecutorStats {
        match self {
            ExecutorEnum::Start(exec) => exec.stats_mut(),
            ExecutorEnum::Base(exec) => exec.stats_mut(),
            ExecutorEnum::GetVertices(exec) => exec.stats_mut(),
            ExecutorEnum::GetNeighbors(exec) => exec.stats_mut(),
            ExecutorEnum::GetProp(exec) => exec.stats_mut(),
            ExecutorEnum::AllPaths(exec) => exec.stats_mut(),
            ExecutorEnum::Expand(exec) => exec.stats_mut(),
            ExecutorEnum::ExpandAll(exec) => exec.stats_mut(),
            ExecutorEnum::Traverse(exec) => exec.stats_mut(),
            ExecutorEnum::ShortestPath(exec) => exec.stats_mut(),
            ExecutorEnum::MultiShortestPath(exec) => exec.stats_mut(),
            ExecutorEnum::InnerJoin(exec) => exec.stats_mut(),
            ExecutorEnum::HashInnerJoin(exec) => exec.stats_mut(),
            ExecutorEnum::LeftJoin(exec) => exec.stats_mut(),
            ExecutorEnum::HashLeftJoin(exec) => exec.stats_mut(),
            ExecutorEnum::CrossJoin(exec) => exec.stats_mut(),
            ExecutorEnum::Union(exec) => exec.stats_mut(),
            ExecutorEnum::UnionAll(exec) => exec.stats_mut(),
            ExecutorEnum::Minus(exec) => exec.stats_mut(),
            ExecutorEnum::Intersect(exec) => exec.stats_mut(),
            ExecutorEnum::Filter(exec) => exec.stats_mut(),
            ExecutorEnum::Project(exec) => exec.stats_mut(),
            ExecutorEnum::Limit(exec) => exec.stats_mut(),
            ExecutorEnum::Sort(exec) => exec.stats_mut(),
            ExecutorEnum::TopN(exec) => exec.stats_mut(),
            ExecutorEnum::Sample(exec) => exec.stats_mut(),
            ExecutorEnum::Aggregate(exec) => exec.stats_mut(),
            ExecutorEnum::GroupBy(exec) => exec.stats_mut(),
            ExecutorEnum::Having(exec) => exec.stats_mut(),
            ExecutorEnum::Dedup(exec) => exec.stats_mut(),
            ExecutorEnum::Unwind(exec) => exec.stats_mut(),
            ExecutorEnum::Assign(exec) => exec.stats_mut(),
            ExecutorEnum::AppendVertices(exec) => exec.stats_mut(),
            ExecutorEnum::RollUpApply(exec) => exec.stats_mut(),
            ExecutorEnum::PatternApply(exec) => exec.stats_mut(),
            ExecutorEnum::Loop(exec) => exec.stats_mut(),
            ExecutorEnum::ForLoop(exec) => exec.stats_mut(),
            ExecutorEnum::WhileLoop(exec) => exec.stats_mut(),
            ExecutorEnum::CreateSpace(exec) => exec.stats_mut(),
            ExecutorEnum::DropSpace(exec) => exec.stats_mut(),
            ExecutorEnum::DescSpace(exec) => exec.stats_mut(),
            ExecutorEnum::CreateTag(exec) => exec.stats_mut(),
            ExecutorEnum::AlterTag(exec) => exec.stats_mut(),
            ExecutorEnum::DescTag(exec) => exec.stats_mut(),
            ExecutorEnum::DropTag(exec) => exec.stats_mut(),
            ExecutorEnum::CreateEdge(exec) => exec.stats_mut(),
            ExecutorEnum::AlterEdge(exec) => exec.stats_mut(),
            ExecutorEnum::DescEdge(exec) => exec.stats_mut(),
            ExecutorEnum::DropEdge(exec) => exec.stats_mut(),
            ExecutorEnum::InsertVertex(exec) => exec.stats_mut(),
            ExecutorEnum::InsertEdge(exec) => exec.stats_mut(),
            ExecutorEnum::Update(exec) => exec.stats_mut(),
            ExecutorEnum::ChangePassword(exec) => exec.stats_mut(),
        }
    }
}

#[async_trait]
impl<S: StorageEngine + Send + 'static> super::base::Executor<S> for ExecutorEnum<S> {
    async fn execute(&mut self) -> DBResult<ExecutionResult> {
        let start = Instant::now();
        let result = match self {
            ExecutorEnum::Start(exec) => exec.execute().await,
            ExecutorEnum::Base(exec) => exec.execute().await,
            ExecutorEnum::GetVertices(exec) => exec.execute().await,
            ExecutorEnum::GetNeighbors(exec) => exec.execute().await,
            ExecutorEnum::GetProp(exec) => exec.execute().await,
            ExecutorEnum::AllPaths(exec) => exec.execute().await,
            ExecutorEnum::Expand(exec) => exec.execute().await,
            ExecutorEnum::ExpandAll(exec) => exec.execute().await,
            ExecutorEnum::Traverse(exec) => exec.execute().await,
            ExecutorEnum::ShortestPath(exec) => exec.execute().await,
            ExecutorEnum::MultiShortestPath(exec) => exec.execute().await,
            ExecutorEnum::InnerJoin(exec) => exec.execute().await,
            ExecutorEnum::HashInnerJoin(exec) => exec.execute().await,
            ExecutorEnum::LeftJoin(exec) => exec.execute().await,
            ExecutorEnum::HashLeftJoin(exec) => exec.execute().await,
            ExecutorEnum::CrossJoin(exec) => exec.execute().await,
            ExecutorEnum::Union(exec) => exec.execute().await,
            ExecutorEnum::UnionAll(exec) => exec.execute().await,
            ExecutorEnum::Minus(exec) => exec.execute().await,
            ExecutorEnum::Intersect(exec) => exec.execute().await,
            ExecutorEnum::Filter(exec) => exec.execute().await,
            ExecutorEnum::Project(exec) => exec.execute().await,
            ExecutorEnum::Limit(exec) => exec.execute().await,
            ExecutorEnum::Sort(exec) => exec.execute().await,
            ExecutorEnum::TopN(exec) => exec.execute().await,
            ExecutorEnum::Sample(exec) => exec.execute().await,
            ExecutorEnum::Aggregate(exec) => exec.execute().await,
            ExecutorEnum::GroupBy(exec) => exec.execute().await,
            ExecutorEnum::Having(exec) => exec.execute().await,
            ExecutorEnum::Dedup(exec) => exec.execute().await,
            ExecutorEnum::Unwind(exec) => exec.execute().await,
            ExecutorEnum::Assign(exec) => exec.execute().await,
            ExecutorEnum::AppendVertices(exec) => exec.execute().await,
            ExecutorEnum::RollUpApply(exec) => exec.execute().await,
            ExecutorEnum::PatternApply(exec) => exec.execute().await,
            ExecutorEnum::Loop(exec) => exec.execute().await,
            ExecutorEnum::ForLoop(exec) => exec.execute().await,
            ExecutorEnum::WhileLoop(exec) => exec.execute().await,
            ExecutorEnum::CreateSpace(exec) => exec.execute().await,
            ExecutorEnum::DropSpace(exec) => exec.execute().await,
            ExecutorEnum::DescSpace(exec) => exec.execute().await,
            ExecutorEnum::CreateTag(exec) => exec.execute().await,
            ExecutorEnum::AlterTag(exec) => exec.execute().await,
            ExecutorEnum::DescTag(exec) => exec.execute().await,
            ExecutorEnum::DropTag(exec) => exec.execute().await,
            ExecutorEnum::CreateEdge(exec) => exec.execute().await,
            ExecutorEnum::AlterEdge(exec) => exec.execute().await,
            ExecutorEnum::DescEdge(exec) => exec.execute().await,
            ExecutorEnum::DropEdge(exec) => exec.execute().await,
            ExecutorEnum::InsertVertex(exec) => exec.execute().await,
            ExecutorEnum::InsertEdge(exec) => exec.execute().await,
            ExecutorEnum::Update(exec) => exec.execute().await,
            ExecutorEnum::ChangePassword(exec) => exec.execute().await,
        };
        self.stats_mut().add_total_time(start.elapsed());
        result
    }

    fn open(&mut self) -> DBResult<()> {
        match self {
            ExecutorEnum::Start(exec) => exec.open(),
            ExecutorEnum::Base(exec) => exec.open(),
            ExecutorEnum::GetVertices(exec) => exec.open(),
            ExecutorEnum::GetNeighbors(exec) => exec.open(),
            ExecutorEnum::GetProp(exec) => exec.open(),
            ExecutorEnum::AllPaths(exec) => exec.open(),
            ExecutorEnum::Expand(exec) => exec.open(),
            ExecutorEnum::ExpandAll(exec) => exec.open(),
            ExecutorEnum::Traverse(exec) => exec.open(),
            ExecutorEnum::ShortestPath(exec) => exec.open(),
            ExecutorEnum::MultiShortestPath(exec) => exec.open(),
            ExecutorEnum::InnerJoin(exec) => exec.open(),
            ExecutorEnum::HashInnerJoin(exec) => exec.open(),
            ExecutorEnum::LeftJoin(exec) => exec.open(),
            ExecutorEnum::HashLeftJoin(exec) => exec.open(),
            ExecutorEnum::CrossJoin(exec) => exec.open(),
            ExecutorEnum::Union(exec) => exec.open(),
            ExecutorEnum::UnionAll(exec) => exec.open(),
            ExecutorEnum::Minus(exec) => exec.open(),
            ExecutorEnum::Intersect(exec) => exec.open(),
            ExecutorEnum::Filter(exec) => exec.open(),
            ExecutorEnum::Project(exec) => exec.open(),
            ExecutorEnum::Limit(exec) => exec.open(),
            ExecutorEnum::Sort(exec) => exec.open(),
            ExecutorEnum::TopN(exec) => exec.open(),
            ExecutorEnum::Sample(exec) => exec.open(),
            ExecutorEnum::Aggregate(exec) => exec.open(),
            ExecutorEnum::GroupBy(exec) => exec.open(),
            ExecutorEnum::Having(exec) => exec.open(),
            ExecutorEnum::Dedup(exec) => exec.open(),
            ExecutorEnum::Unwind(exec) => exec.open(),
            ExecutorEnum::Assign(exec) => exec.open(),
            ExecutorEnum::AppendVertices(exec) => exec.open(),
            ExecutorEnum::RollUpApply(exec) => exec.open(),
            ExecutorEnum::PatternApply(exec) => exec.open(),
            ExecutorEnum::Loop(exec) => exec.open(),
            ExecutorEnum::ForLoop(exec) => exec.open(),
            ExecutorEnum::WhileLoop(exec) => exec.open(),
            ExecutorEnum::CreateSpace(exec) => exec.open(),
            ExecutorEnum::DropSpace(exec) => exec.open(),
            ExecutorEnum::DescSpace(exec) => exec.open(),
            ExecutorEnum::CreateTag(exec) => exec.open(),
            ExecutorEnum::AlterTag(exec) => exec.open(),
            ExecutorEnum::DescTag(exec) => exec.open(),
            ExecutorEnum::DropTag(exec) => exec.open(),
            ExecutorEnum::CreateEdge(exec) => exec.open(),
            ExecutorEnum::AlterEdge(exec) => exec.open(),
            ExecutorEnum::DescEdge(exec) => exec.open(),
            ExecutorEnum::DropEdge(exec) => exec.open(),
            ExecutorEnum::InsertVertex(exec) => exec.open(),
            ExecutorEnum::InsertEdge(exec) => exec.open(),
            ExecutorEnum::Update(exec) => exec.open(),
            ExecutorEnum::ChangePassword(exec) => exec.open(),
        }
    }

    fn close(&mut self) -> DBResult<()> {
        match self {
            ExecutorEnum::Start(exec) => exec.close(),
            ExecutorEnum::Base(exec) => exec.close(),
            ExecutorEnum::GetVertices(exec) => exec.close(),
            ExecutorEnum::GetNeighbors(exec) => exec.close(),
            ExecutorEnum::GetProp(exec) => exec.close(),
            ExecutorEnum::AllPaths(exec) => exec.close(),
            ExecutorEnum::Expand(exec) => exec.close(),
            ExecutorEnum::ExpandAll(exec) => exec.close(),
            ExecutorEnum::Traverse(exec) => exec.close(),
            ExecutorEnum::ShortestPath(exec) => exec.close(),
            ExecutorEnum::MultiShortestPath(exec) => exec.close(),
            ExecutorEnum::InnerJoin(exec) => exec.close(),
            ExecutorEnum::HashInnerJoin(exec) => exec.close(),
            ExecutorEnum::LeftJoin(exec) => exec.close(),
            ExecutorEnum::HashLeftJoin(exec) => exec.close(),
            ExecutorEnum::CrossJoin(exec) => exec.close(),
            ExecutorEnum::Union(exec) => exec.close(),
            ExecutorEnum::UnionAll(exec) => exec.close(),
            ExecutorEnum::Minus(exec) => exec.close(),
            ExecutorEnum::Intersect(exec) => exec.close(),
            ExecutorEnum::Filter(exec) => exec.close(),
            ExecutorEnum::Project(exec) => exec.close(),
            ExecutorEnum::Limit(exec) => exec.close(),
            ExecutorEnum::Sort(exec) => exec.close(),
            ExecutorEnum::TopN(exec) => exec.close(),
            ExecutorEnum::Sample(exec) => exec.close(),
            ExecutorEnum::Aggregate(exec) => exec.close(),
            ExecutorEnum::GroupBy(exec) => exec.close(),
            ExecutorEnum::Having(exec) => exec.close(),
            ExecutorEnum::Dedup(exec) => exec.close(),
            ExecutorEnum::Unwind(exec) => exec.close(),
            ExecutorEnum::Assign(exec) => exec.close(),
            ExecutorEnum::AppendVertices(exec) => exec.close(),
            ExecutorEnum::RollUpApply(exec) => exec.close(),
            ExecutorEnum::PatternApply(exec) => exec.close(),
            ExecutorEnum::Loop(exec) => exec.close(),
            ExecutorEnum::ForLoop(exec) => exec.close(),
            ExecutorEnum::WhileLoop(exec) => exec.close(),
            ExecutorEnum::CreateSpace(exec) => exec.close(),
            ExecutorEnum::DropSpace(exec) => exec.close(),
            ExecutorEnum::DescSpace(exec) => exec.close(),
            ExecutorEnum::CreateTag(exec) => exec.close(),
            ExecutorEnum::AlterTag(exec) => exec.close(),
            ExecutorEnum::DescTag(exec) => exec.close(),
            ExecutorEnum::DropTag(exec) => exec.close(),
            ExecutorEnum::CreateEdge(exec) => exec.close(),
            ExecutorEnum::AlterEdge(exec) => exec.close(),
            ExecutorEnum::DescEdge(exec) => exec.close(),
            ExecutorEnum::DropEdge(exec) => exec.close(),
            ExecutorEnum::InsertVertex(exec) => exec.close(),
            ExecutorEnum::InsertEdge(exec) => exec.close(),
            ExecutorEnum::Update(exec) => exec.close(),
            ExecutorEnum::ChangePassword(exec) => exec.close(),
        }
    }

    fn is_open(&self) -> bool {
        match self {
            ExecutorEnum::Start(exec) => exec.is_open(),
            ExecutorEnum::Base(exec) => exec.is_open(),
            ExecutorEnum::GetVertices(exec) => exec.is_open(),
            ExecutorEnum::GetNeighbors(exec) => exec.is_open(),
            ExecutorEnum::GetProp(exec) => exec.is_open(),
            ExecutorEnum::AllPaths(exec) => exec.is_open(),
            ExecutorEnum::Expand(exec) => exec.is_open(),
            ExecutorEnum::ExpandAll(exec) => exec.is_open(),
            ExecutorEnum::Traverse(exec) => exec.is_open(),
            ExecutorEnum::ShortestPath(exec) => exec.is_open(),
            ExecutorEnum::MultiShortestPath(exec) => exec.is_open(),
            ExecutorEnum::InnerJoin(exec) => exec.is_open(),
            ExecutorEnum::HashInnerJoin(exec) => exec.is_open(),
            ExecutorEnum::LeftJoin(exec) => exec.is_open(),
            ExecutorEnum::HashLeftJoin(exec) => exec.is_open(),
            ExecutorEnum::CrossJoin(exec) => exec.is_open(),
            ExecutorEnum::Union(exec) => exec.is_open(),
            ExecutorEnum::UnionAll(exec) => exec.is_open(),
            ExecutorEnum::Minus(exec) => exec.is_open(),
            ExecutorEnum::Intersect(exec) => exec.is_open(),
            ExecutorEnum::Filter(exec) => exec.is_open(),
            ExecutorEnum::Project(exec) => exec.is_open(),
            ExecutorEnum::Limit(exec) => exec.is_open(),
            ExecutorEnum::Sort(exec) => exec.is_open(),
            ExecutorEnum::TopN(exec) => exec.is_open(),
            ExecutorEnum::Sample(exec) => exec.is_open(),
            ExecutorEnum::Aggregate(exec) => exec.is_open(),
            ExecutorEnum::GroupBy(exec) => exec.is_open(),
            ExecutorEnum::Having(exec) => exec.is_open(),
            ExecutorEnum::Dedup(exec) => exec.is_open(),
            ExecutorEnum::Unwind(exec) => exec.is_open(),
            ExecutorEnum::Assign(exec) => exec.is_open(),
            ExecutorEnum::AppendVertices(exec) => exec.is_open(),
            ExecutorEnum::RollUpApply(exec) => exec.is_open(),
            ExecutorEnum::PatternApply(exec) => exec.is_open(),
            ExecutorEnum::Loop(exec) => exec.is_open(),
            ExecutorEnum::ForLoop(exec) => exec.is_open(),
            ExecutorEnum::WhileLoop(exec) => exec.is_open(),
            ExecutorEnum::CreateSpace(exec) => exec.is_open(),
            ExecutorEnum::DropSpace(exec) => exec.is_open(),
            ExecutorEnum::DescSpace(exec) => exec.is_open(),
            ExecutorEnum::CreateTag(exec) => exec.is_open(),
            ExecutorEnum::AlterTag(exec) => exec.is_open(),
            ExecutorEnum::DescTag(exec) => exec.is_open(),
            ExecutorEnum::DropTag(exec) => exec.is_open(),
            ExecutorEnum::CreateEdge(exec) => exec.is_open(),
            ExecutorEnum::AlterEdge(exec) => exec.is_open(),
            ExecutorEnum::DescEdge(exec) => exec.is_open(),
            ExecutorEnum::DropEdge(exec) => exec.is_open(),
            ExecutorEnum::InsertVertex(exec) => exec.is_open(),
            ExecutorEnum::InsertEdge(exec) => exec.is_open(),
            ExecutorEnum::Update(exec) => exec.is_open(),
            ExecutorEnum::ChangePassword(exec) => exec.is_open(),
        }
    }

    fn id(&self) -> i64 {
        self.id()
    }

    fn name(&self) -> &str {
        self.name()
    }

    fn description(&self) -> &str {
        self.name()
    }

    fn stats(&self) -> &ExecutorStats {
        match self {
            ExecutorEnum::Start(exec) => exec.stats(),
            ExecutorEnum::Base(exec) => exec.stats(),
            ExecutorEnum::GetVertices(exec) => exec.stats(),
            ExecutorEnum::GetNeighbors(exec) => exec.stats(),
            ExecutorEnum::GetProp(exec) => exec.stats(),
            ExecutorEnum::AllPaths(exec) => exec.stats(),
            ExecutorEnum::Expand(exec) => exec.stats(),
            ExecutorEnum::ExpandAll(exec) => exec.stats(),
            ExecutorEnum::Traverse(exec) => exec.stats(),
            ExecutorEnum::ShortestPath(exec) => exec.stats(),
            ExecutorEnum::MultiShortestPath(exec) => exec.stats(),
            ExecutorEnum::InnerJoin(exec) => exec.stats(),
            ExecutorEnum::HashInnerJoin(exec) => exec.stats(),
            ExecutorEnum::LeftJoin(exec) => exec.stats(),
            ExecutorEnum::HashLeftJoin(exec) => exec.stats(),
            ExecutorEnum::CrossJoin(exec) => exec.stats(),
            ExecutorEnum::Union(exec) => exec.stats(),
            ExecutorEnum::UnionAll(exec) => exec.stats(),
            ExecutorEnum::Minus(exec) => exec.stats(),
            ExecutorEnum::Intersect(exec) => exec.stats(),
            ExecutorEnum::Filter(exec) => exec.stats(),
            ExecutorEnum::Project(exec) => exec.stats(),
            ExecutorEnum::Limit(exec) => exec.stats(),
            ExecutorEnum::Sort(exec) => exec.stats(),
            ExecutorEnum::TopN(exec) => exec.stats(),
            ExecutorEnum::Sample(exec) => exec.stats(),
            ExecutorEnum::Aggregate(exec) => exec.stats(),
            ExecutorEnum::GroupBy(exec) => exec.stats(),
            ExecutorEnum::Having(exec) => exec.stats(),
            ExecutorEnum::Dedup(exec) => exec.stats(),
            ExecutorEnum::Unwind(exec) => exec.stats(),
            ExecutorEnum::Assign(exec) => exec.stats(),
            ExecutorEnum::AppendVertices(exec) => exec.stats(),
            ExecutorEnum::RollUpApply(exec) => exec.stats(),
            ExecutorEnum::PatternApply(exec) => exec.stats(),
            ExecutorEnum::Loop(exec) => exec.stats(),
            ExecutorEnum::ForLoop(exec) => exec.stats(),
            ExecutorEnum::WhileLoop(exec) => exec.stats(),
            ExecutorEnum::CreateSpace(exec) => exec.stats(),
            ExecutorEnum::DropSpace(exec) => exec.stats(),
            ExecutorEnum::DescSpace(exec) => exec.stats(),
            ExecutorEnum::CreateTag(exec) => exec.stats(),
            ExecutorEnum::AlterTag(exec) => exec.stats(),
            ExecutorEnum::DescTag(exec) => exec.stats(),
            ExecutorEnum::DropTag(exec) => exec.stats(),
            ExecutorEnum::CreateEdge(exec) => exec.stats(),
            ExecutorEnum::AlterEdge(exec) => exec.stats(),
            ExecutorEnum::DescEdge(exec) => exec.stats(),
            ExecutorEnum::DropEdge(exec) => exec.stats(),
            ExecutorEnum::InsertVertex(exec) => exec.stats(),
            ExecutorEnum::InsertEdge(exec) => exec.stats(),
            ExecutorEnum::Update(exec) => exec.stats(),
            ExecutorEnum::ChangePassword(exec) => exec.stats(),
        }
    }

    fn stats_mut(&mut self) -> &mut ExecutorStats {
        match self {
            ExecutorEnum::Start(exec) => exec.stats_mut(),
            ExecutorEnum::Base(exec) => exec.stats_mut(),
            ExecutorEnum::GetVertices(exec) => exec.stats_mut(),
            ExecutorEnum::GetNeighbors(exec) => exec.stats_mut(),
            ExecutorEnum::GetProp(exec) => exec.stats_mut(),
            ExecutorEnum::AllPaths(exec) => exec.stats_mut(),
            ExecutorEnum::Expand(exec) => exec.stats_mut(),
            ExecutorEnum::ExpandAll(exec) => exec.stats_mut(),
            ExecutorEnum::Traverse(exec) => exec.stats_mut(),
            ExecutorEnum::ShortestPath(exec) => exec.stats_mut(),
            ExecutorEnum::MultiShortestPath(exec) => exec.stats_mut(),
            ExecutorEnum::InnerJoin(exec) => exec.stats_mut(),
            ExecutorEnum::HashInnerJoin(exec) => exec.stats_mut(),
            ExecutorEnum::LeftJoin(exec) => exec.stats_mut(),
            ExecutorEnum::HashLeftJoin(exec) => exec.stats_mut(),
            ExecutorEnum::CrossJoin(exec) => exec.stats_mut(),
            ExecutorEnum::Union(exec) => exec.stats_mut(),
            ExecutorEnum::UnionAll(exec) => exec.stats_mut(),
            ExecutorEnum::Minus(exec) => exec.stats_mut(),
            ExecutorEnum::Intersect(exec) => exec.stats_mut(),
            ExecutorEnum::Filter(exec) => exec.stats_mut(),
            ExecutorEnum::Project(exec) => exec.stats_mut(),
            ExecutorEnum::Limit(exec) => exec.stats_mut(),
            ExecutorEnum::Sort(exec) => exec.stats_mut(),
            ExecutorEnum::TopN(exec) => exec.stats_mut(),
            ExecutorEnum::Sample(exec) => exec.stats_mut(),
            ExecutorEnum::Aggregate(exec) => exec.stats_mut(),
            ExecutorEnum::GroupBy(exec) => exec.stats_mut(),
            ExecutorEnum::Having(exec) => exec.stats_mut(),
            ExecutorEnum::Dedup(exec) => exec.stats_mut(),
            ExecutorEnum::Unwind(exec) => exec.stats_mut(),
            ExecutorEnum::Assign(exec) => exec.stats_mut(),
            ExecutorEnum::AppendVertices(exec) => exec.stats_mut(),
            ExecutorEnum::RollUpApply(exec) => exec.stats_mut(),
            ExecutorEnum::PatternApply(exec) => exec.stats_mut(),
            ExecutorEnum::Loop(exec) => exec.stats_mut(),
            ExecutorEnum::ForLoop(exec) => exec.stats_mut(),
            ExecutorEnum::WhileLoop(exec) => exec.stats_mut(),
            ExecutorEnum::CreateSpace(exec) => exec.stats_mut(),
            ExecutorEnum::DropSpace(exec) => exec.stats_mut(),
            ExecutorEnum::DescSpace(exec) => exec.stats_mut(),
            ExecutorEnum::CreateTag(exec) => exec.stats_mut(),
            ExecutorEnum::AlterTag(exec) => exec.stats_mut(),
            ExecutorEnum::DescTag(exec) => exec.stats_mut(),
            ExecutorEnum::DropTag(exec) => exec.stats_mut(),
            ExecutorEnum::CreateEdge(exec) => exec.stats_mut(),
            ExecutorEnum::AlterEdge(exec) => exec.stats_mut(),
            ExecutorEnum::DescEdge(exec) => exec.stats_mut(),
            ExecutorEnum::DropEdge(exec) => exec.stats_mut(),
            ExecutorEnum::InsertVertex(exec) => exec.stats_mut(),
            ExecutorEnum::InsertEdge(exec) => exec.stats_mut(),
            ExecutorEnum::Update(exec) => exec.stats_mut(),
            ExecutorEnum::ChangePassword(exec) => exec.stats_mut(),
        }
    }
}

impl<S: StorageEngine + Send + 'static> InputExecutor<S> for ExecutorEnum<S> {
    fn set_input(&mut self, input: ExecutorEnum<S>) {
        match self {
            ExecutorEnum::Filter(exec) => exec.set_input(input),
            ExecutorEnum::Project(exec) => exec.set_input(input),
            ExecutorEnum::Limit(exec) => exec.set_input(input),
            ExecutorEnum::Sort(exec) => exec.set_input(input),
            ExecutorEnum::TopN(exec) => exec.set_input(input),
            ExecutorEnum::Sample(exec) => exec.set_input(input),
            ExecutorEnum::Dedup(exec) => exec.set_input(input),
            ExecutorEnum::Expand(exec) => exec.set_input(input),
            ExecutorEnum::ExpandAll(exec) => exec.set_input(input),
            ExecutorEnum::Traverse(exec) => exec.set_input(input),
            ExecutorEnum::ShortestPath(exec) => exec.set_input(input),
            ExecutorEnum::MultiShortestPath(exec) => exec.set_input(input),
            ExecutorEnum::Aggregate(exec) => exec.set_input(input),
            ExecutorEnum::GroupBy(exec) => exec.set_input(input),
            ExecutorEnum::Having(exec) => exec.set_input(input),
            ExecutorEnum::Unwind(_) => {}
            ExecutorEnum::Assign(_) => {}
            ExecutorEnum::AppendVertices(_) => {}
            ExecutorEnum::PatternApply(_) => {}
            ExecutorEnum::RollUpApply(_) => {}
            ExecutorEnum::Loop(_) => {}
            ExecutorEnum::ForLoop(_) => {}
            ExecutorEnum::WhileLoop(_) => {}
            ExecutorEnum::InnerJoin(_) => {}
            ExecutorEnum::HashInnerJoin(_) => {}
            ExecutorEnum::LeftJoin(_) => {}
            ExecutorEnum::HashLeftJoin(_) => {}
            ExecutorEnum::CrossJoin(_) => {}
            ExecutorEnum::Start(_) => {}
            ExecutorEnum::Base(_) => {}
            ExecutorEnum::GetVertices(_) => {}
            ExecutorEnum::GetNeighbors(_) => {}
            ExecutorEnum::GetProp(_) => {}
            ExecutorEnum::AllPaths(_) => {}
            ExecutorEnum::Union(_) => {}
            ExecutorEnum::UnionAll(_) => {}
            ExecutorEnum::Minus(_) => {}
            ExecutorEnum::Intersect(_) => {}
            ExecutorEnum::CreateSpace(_) => {}
            ExecutorEnum::DropSpace(_) => {}
            ExecutorEnum::DescSpace(_) => {}
            ExecutorEnum::CreateTag(_) => {}
            ExecutorEnum::AlterTag(_) => {}
            ExecutorEnum::DescTag(_) => {}
            ExecutorEnum::DropTag(_) => {}
            ExecutorEnum::CreateEdge(_) => {}
            ExecutorEnum::AlterEdge(_) => {}
            ExecutorEnum::DescEdge(_) => {}
            ExecutorEnum::DropEdge(_) => {}
            ExecutorEnum::InsertVertex(_) => {}
            ExecutorEnum::InsertEdge(_) => {}
            ExecutorEnum::Update(_) => {}
            ExecutorEnum::ChangePassword(_) => {}
        }
    }

    fn get_input(&self) -> Option<&ExecutorEnum<S>> {
        match self {
            ExecutorEnum::Filter(exec) => exec.get_input(),
            ExecutorEnum::Project(exec) => exec.get_input(),
            ExecutorEnum::Limit(exec) => exec.get_input(),
            ExecutorEnum::Sort(exec) => exec.get_input(),
            ExecutorEnum::TopN(exec) => exec.get_input(),
            ExecutorEnum::Sample(exec) => exec.get_input(),
            ExecutorEnum::Dedup(exec) => exec.get_input(),
            ExecutorEnum::Expand(exec) => exec.get_input(),
            ExecutorEnum::ExpandAll(exec) => exec.get_input(),
            ExecutorEnum::Traverse(exec) => exec.get_input(),
            ExecutorEnum::ShortestPath(exec) => exec.get_input(),
            ExecutorEnum::MultiShortestPath(exec) => exec.get_input(),
            ExecutorEnum::Aggregate(exec) => exec.get_input(),
            ExecutorEnum::GroupBy(exec) => exec.get_input(),
            ExecutorEnum::Having(exec) => exec.get_input(),
            ExecutorEnum::Unwind(_) => None,
            ExecutorEnum::Assign(_) => None,
            ExecutorEnum::AppendVertices(_) => None,
            ExecutorEnum::PatternApply(_) => None,
            ExecutorEnum::RollUpApply(_) => None,
            ExecutorEnum::Loop(_) => None,
            ExecutorEnum::ForLoop(_) => None,
            ExecutorEnum::WhileLoop(_) => None,
            ExecutorEnum::InnerJoin(_) => None,
            ExecutorEnum::HashInnerJoin(_) => None,
            ExecutorEnum::LeftJoin(_) => None,
            ExecutorEnum::HashLeftJoin(_) => None,
            ExecutorEnum::CrossJoin(_) => None,
            ExecutorEnum::Start(_) => None,
            ExecutorEnum::Base(_) => None,
            ExecutorEnum::GetVertices(_) => None,
            ExecutorEnum::GetNeighbors(_) => None,
            ExecutorEnum::GetProp(_) => None,
            ExecutorEnum::AllPaths(_) => None,
            ExecutorEnum::Union(_) => None,
            ExecutorEnum::UnionAll(_) => None,
            ExecutorEnum::Minus(_) => None,
            ExecutorEnum::Intersect(_) => None,
            ExecutorEnum::CreateSpace(_) => None,
            ExecutorEnum::DropSpace(_) => None,
            ExecutorEnum::DescSpace(_) => None,
            ExecutorEnum::CreateTag(_) => None,
            ExecutorEnum::AlterTag(_) => None,
            ExecutorEnum::DescTag(_) => None,
            ExecutorEnum::DropTag(_) => None,
            ExecutorEnum::CreateEdge(_) => None,
            ExecutorEnum::AlterEdge(_) => None,
            ExecutorEnum::DescEdge(_) => None,
            ExecutorEnum::DropEdge(_) => None,
            ExecutorEnum::InsertVertex(_) => None,
            ExecutorEnum::InsertEdge(_) => None,
            ExecutorEnum::Update(_) => None,
            ExecutorEnum::ChangePassword(_) => None,
        }
    }
}

pub trait ChainableExecutor<S: StorageEngine + Send + 'static>:
    super::base::Executor<S> + InputExecutor<S>
{
    fn into_executor_enum(self) -> ExecutorEnum<S>
    where
        Self: Sized + 'static;
}

impl<S: StorageEngine + Send + 'static> ChainableExecutor<S> for ExecutorEnum<S> {
    fn into_executor_enum(self) -> ExecutorEnum<S> {
        self
    }
}
