//! 执行器枚举定义
//!
//! 使用静态分发替代动态分发，所有执行器类型都包含在此枚举中
//! 通过为枚举实现 Executor trait，可以统一处理所有执行器类型

use std::fmt;

use std::fmt::{Debug, Formatter};
use std::time::Instant;

use crate::storage::StorageClient;

use super::admin::{
    AlterEdgeExecutor, AlterTagExecutor, ChangePasswordExecutor, CreateEdgeExecutor,
    CreateSpaceExecutor, CreateTagExecutor, CreateUserExecutor, AlterUserExecutor, DropUserExecutor,
    DescEdgeExecutor, DescSpaceExecutor, DescTagExecutor,
    DropEdgeExecutor, DropSpaceExecutor, DropTagExecutor, ShowSpacesExecutor, ShowTagsExecutor, ShowEdgesExecutor,
    CreateTagIndexExecutor, DropTagIndexExecutor, DescTagIndexExecutor, ShowTagIndexesExecutor,
    RebuildTagIndexExecutor, CreateEdgeIndexExecutor, DropEdgeIndexExecutor, DescEdgeIndexExecutor,
    ShowEdgeIndexesExecutor, RebuildEdgeIndexExecutor,
};

use super::base::{BaseExecutor, ExecutorStats, StartExecutor, ExecutionResult, DBResult, Executor, InputExecutor};
use super::data_access::{
    AllPathsExecutor, GetNeighborsExecutor, GetPropExecutor, GetVerticesExecutor,
    ScanEdgesExecutor, ScanVerticesExecutor,
};
use super::data_processing::graph_traversal::{
    ExpandAllExecutor, ExpandExecutor, MultiShortestPathExecutor, ShortestPathExecutor,
    TraverseExecutor,
};
use super::data_processing::join::{CrossJoinExecutor, HashInnerJoinExecutor, HashLeftJoinExecutor, InnerJoinExecutor, LeftJoinExecutor};
use super::data_processing::set_operations::{IntersectExecutor, MinusExecutor, UnionAllExecutor, UnionExecutor};
use super::logic::{ForLoopExecutor, LoopExecutor, SelectExecutor, WhileLoopExecutor};
use super::result_processing::{
    AggregateExecutor, DedupExecutor, FilterExecutor, GroupByExecutor, HavingExecutor,
    LimitExecutor, ProjectExecutor, SampleExecutor, SortExecutor, TopNExecutor,
};
use super::result_processing::transformations::{
    AppendVerticesExecutor, AssignExecutor, PatternApplyExecutor, RollUpApplyExecutor, UnwindExecutor,
};
use super::search_executors::BFSShortestExecutor;
use super::search_executors::IndexScanExecutor;
use super::special_executors::{ArgumentExecutor, DataCollectExecutor, PassThroughExecutor};

pub enum ExecutorEnum<S: StorageClient + Send + 'static> {
    Start(StartExecutor<S>),
    Base(BaseExecutor<S>),
    GetVertices(GetVerticesExecutor<S>),
    GetNeighbors(GetNeighborsExecutor<S>),
    GetProp(GetPropExecutor<S>),
    AllPaths(AllPathsExecutor<S>),
    Expand(ExpandExecutor<S>),
    ExpandAll(ExpandAllExecutor<S>),
    Traverse(TraverseExecutor<S>),
    ShortestPath(ShortestPathExecutor<S>),
    MultiShortestPath(MultiShortestPathExecutor<S>),
    InnerJoin(InnerJoinExecutor<S>),
    HashInnerJoin(HashInnerJoinExecutor<S>),
    LeftJoin(LeftJoinExecutor<S>),
    HashLeftJoin(HashLeftJoinExecutor<S>),
    CrossJoin(CrossJoinExecutor<S>),
    Union(UnionExecutor<S>),
    UnionAll(UnionAllExecutor<S>),
    Minus(MinusExecutor<S>),
    Intersect(IntersectExecutor<S>),
    Filter(FilterExecutor<S>),
    Project(ProjectExecutor<S>),
    Limit(LimitExecutor<S>),
    Sort(SortExecutor<S>),
    TopN(TopNExecutor<S>),
    Sample(SampleExecutor<S>),
    Aggregate(AggregateExecutor<S>),
    GroupBy(GroupByExecutor<S>),
    Having(HavingExecutor<S>),
    Dedup(DedupExecutor<S>),
    Unwind(UnwindExecutor<S>),
    Assign(AssignExecutor<S>),
    AppendVertices(AppendVerticesExecutor<S>),
    RollUpApply(RollUpApplyExecutor<S>),
    PatternApply(PatternApplyExecutor<S>),
    Loop(LoopExecutor<S>),
    ForLoop(ForLoopExecutor<S>),
    WhileLoop(WhileLoopExecutor<S>),
    Select(SelectExecutor<S>),
    ScanEdges(ScanEdgesExecutor<S>),
    ScanVertices(ScanVerticesExecutor<S>),
    IndexScan(IndexScanExecutor<S>),
    Argument(ArgumentExecutor<S>),
    PassThrough(PassThroughExecutor<S>),
    DataCollect(DataCollectExecutor<S>),
    BFSShortest(BFSShortestExecutor<S>),
    ShowSpaces(ShowSpacesExecutor<S>),
    ShowTags(ShowTagsExecutor<S>),
    ShowEdges(ShowEdgesExecutor<S>),
    CreateTagIndex(CreateTagIndexExecutor<S>),
    DropTagIndex(DropTagIndexExecutor<S>),
    DescTagIndex(DescTagIndexExecutor<S>),
    ShowTagIndexes(ShowTagIndexesExecutor<S>),
    RebuildTagIndex(RebuildTagIndexExecutor<S>),
    CreateEdgeIndex(CreateEdgeIndexExecutor<S>),
    DropEdgeIndex(DropEdgeIndexExecutor<S>),
    DescEdgeIndex(DescEdgeIndexExecutor<S>),
    ShowEdgeIndexes(ShowEdgeIndexesExecutor<S>),
    RebuildEdgeIndex(RebuildEdgeIndexExecutor<S>),
    CreateSpace(CreateSpaceExecutor<S>),
    DropSpace(DropSpaceExecutor<S>),
    DescSpace(DescSpaceExecutor<S>),
    CreateTag(CreateTagExecutor<S>),
    AlterTag(AlterTagExecutor<S>),
    DescTag(DescTagExecutor<S>),
    DropTag(DropTagExecutor<S>),
    CreateEdge(CreateEdgeExecutor<S>),
    AlterEdge(AlterEdgeExecutor<S>),
    DescEdge(DescEdgeExecutor<S>),
    DropEdge(DropEdgeExecutor<S>),
    CreateUser(CreateUserExecutor<S>),
    AlterUser(AlterUserExecutor<S>),
    DropUser(DropUserExecutor<S>),
    ChangePassword(ChangePasswordExecutor<S>),
}

impl<S: StorageClient + Send + 'static> Debug for ExecutorEnum<S> {
    fn fmt(&self, f: &mut Formatter<'_>) -> fmt::Result {
        match self {
            ExecutorEnum::Start(exec) => f.write_str(&format!("ExecutorEnum::Start({})", exec.name())),
            ExecutorEnum::Base(exec) => f.write_str(&format!("ExecutorEnum::Base({})", exec.name())),
            ExecutorEnum::GetVertices(exec) => f.write_str(&format!("ExecutorEnum::GetVertices({})", exec.name())),
            ExecutorEnum::GetNeighbors(exec) => f.write_str(&format!("ExecutorEnum::GetNeighbors({})", exec.name())),
            ExecutorEnum::GetProp(exec) => f.write_str(&format!("ExecutorEnum::GetProp({})", exec.name())),
            ExecutorEnum::AllPaths(exec) => f.write_str(&format!("ExecutorEnum::AllPaths({})", exec.name())),
            ExecutorEnum::Expand(exec) => f.write_str(&format!("ExecutorEnum::Expand({})", exec.name())),
            ExecutorEnum::ExpandAll(exec) => f.write_str(&format!("ExecutorEnum::ExpandAll({})", exec.name())),
            ExecutorEnum::Traverse(exec) => f.write_str(&format!("ExecutorEnum::Traverse({})", exec.name())),
            ExecutorEnum::ShortestPath(exec) => f.write_str(&format!("ExecutorEnum::ShortestPath({})", exec.name())),
            ExecutorEnum::MultiShortestPath(exec) => f.write_str(&format!("ExecutorEnum::MultiShortestPath({})", exec.name())),
            ExecutorEnum::InnerJoin(exec) => f.write_str(&format!("ExecutorEnum::InnerJoin({})", exec.name())),
            ExecutorEnum::HashInnerJoin(exec) => f.write_str(&format!("ExecutorEnum::HashInnerJoin({})", exec.name())),
            ExecutorEnum::LeftJoin(exec) => f.write_str(&format!("ExecutorEnum::LeftJoin({})", exec.name())),
            ExecutorEnum::HashLeftJoin(exec) => f.write_str(&format!("ExecutorEnum::HashLeftJoin({})", exec.name())),
            ExecutorEnum::CrossJoin(exec) => f.write_str(&format!("ExecutorEnum::CrossJoin({})", exec.name())),
            ExecutorEnum::Union(exec) => f.write_str(&format!("ExecutorEnum::Union({})", exec.name())),
            ExecutorEnum::UnionAll(exec) => f.write_str(&format!("ExecutorEnum::UnionAll({})", exec.name())),
            ExecutorEnum::Minus(exec) => f.write_str(&format!("ExecutorEnum::Minus({})", exec.name())),
            ExecutorEnum::Intersect(exec) => f.write_str(&format!("ExecutorEnum::Intersect({})", exec.name())),
            ExecutorEnum::Filter(exec) => f.write_str(&format!("ExecutorEnum::Filter({})", exec.name())),
            ExecutorEnum::Project(exec) => f.write_str(&format!("ExecutorEnum::Project({})", exec.name())),
            ExecutorEnum::Limit(exec) => f.write_str(&format!("ExecutorEnum::Limit({})", exec.name())),
            ExecutorEnum::Sort(exec) => f.write_str(&format!("ExecutorEnum::Sort({})", exec.name())),
            ExecutorEnum::TopN(exec) => f.write_str(&format!("ExecutorEnum::TopN({})", exec.name())),
            ExecutorEnum::Sample(exec) => f.write_str(&format!("ExecutorEnum::Sample({})", exec.name())),
            ExecutorEnum::Aggregate(exec) => f.write_str(&format!("ExecutorEnum::Aggregate({})", exec.name())),
            ExecutorEnum::GroupBy(exec) => f.write_str(&format!("ExecutorEnum::GroupBy({})", exec.name())),
            ExecutorEnum::Having(exec) => f.write_str(&format!("ExecutorEnum::Having({})", exec.name())),
            ExecutorEnum::Dedup(exec) => f.write_str(&format!("ExecutorEnum::Dedup({})", exec.name())),
            ExecutorEnum::Unwind(exec) => f.write_str(&format!("ExecutorEnum::Unwind({})", exec.name())),
            ExecutorEnum::Assign(exec) => f.write_str(&format!("ExecutorEnum::Assign({})", exec.name())),
            ExecutorEnum::AppendVertices(exec) => f.write_str(&format!("ExecutorEnum::AppendVertices({})", exec.name())),
            ExecutorEnum::RollUpApply(exec) => f.write_str(&format!("ExecutorEnum::RollUpApply({})", exec.name())),
            ExecutorEnum::PatternApply(exec) => f.write_str(&format!("ExecutorEnum::PatternApply({})", exec.name())),
            ExecutorEnum::Loop(exec) => f.write_str(&format!("ExecutorEnum::Loop({})", exec.name())),
            ExecutorEnum::ForLoop(exec) => f.write_str(&format!("ExecutorEnum::ForLoop({})", exec.name())),
            ExecutorEnum::WhileLoop(exec) => f.write_str(&format!("ExecutorEnum::WhileLoop({})", exec.name())),
            ExecutorEnum::Select(exec) => f.write_str(&format!("ExecutorEnum::Select({})", exec.name())),
            ExecutorEnum::ScanEdges(exec) => f.write_str(&format!("ExecutorEnum::ScanEdges({})", exec.name())),
            ExecutorEnum::ScanVertices(exec) => f.write_str(&format!("ExecutorEnum::ScanVertices({})", exec.name())),
            ExecutorEnum::IndexScan(exec) => f.write_str(&format!("ExecutorEnum::IndexScan({})", exec.name())),
            ExecutorEnum::Argument(exec) => f.write_str(&format!("ExecutorEnum::Argument({})", exec.name())),
            ExecutorEnum::PassThrough(exec) => f.write_str(&format!("ExecutorEnum::PassThrough({})", exec.name())),
            ExecutorEnum::DataCollect(exec) => f.write_str(&format!("ExecutorEnum::DataCollect({})", exec.name())),
            ExecutorEnum::BFSShortest(exec) => f.write_str(&format!("ExecutorEnum::BFSShortest({})", exec.name())),
            ExecutorEnum::ShowSpaces(exec) => f.write_str(&format!("ExecutorEnum::ShowSpaces({})", exec.name())),
            ExecutorEnum::ShowTags(exec) => f.write_str(&format!("ExecutorEnum::ShowTags({})", exec.name())),
            ExecutorEnum::ShowEdges(exec) => f.write_str(&format!("ExecutorEnum::ShowEdges({})", exec.name())),
            ExecutorEnum::CreateTagIndex(exec) => f.write_str(&format!("ExecutorEnum::CreateTagIndex({})", exec.name())),
            ExecutorEnum::DropTagIndex(exec) => f.write_str(&format!("ExecutorEnum::DropTagIndex({})", exec.name())),
            ExecutorEnum::DescTagIndex(exec) => f.write_str(&format!("ExecutorEnum::DescTagIndex({})", exec.name())),
            ExecutorEnum::ShowTagIndexes(exec) => f.write_str(&format!("ExecutorEnum::ShowTagIndexes({})", exec.name())),
            ExecutorEnum::RebuildTagIndex(exec) => f.write_str(&format!("ExecutorEnum::RebuildTagIndex({})", exec.name())),
            ExecutorEnum::CreateEdgeIndex(exec) => f.write_str(&format!("ExecutorEnum::CreateEdgeIndex({})", exec.name())),
            ExecutorEnum::DropEdgeIndex(exec) => f.write_str(&format!("ExecutorEnum::DropEdgeIndex({})", exec.name())),
            ExecutorEnum::DescEdgeIndex(exec) => f.write_str(&format!("ExecutorEnum::DescEdgeIndex({})", exec.name())),
            ExecutorEnum::ShowEdgeIndexes(exec) => f.write_str(&format!("ExecutorEnum::ShowEdgeIndexes({})", exec.name())),
            ExecutorEnum::RebuildEdgeIndex(exec) => f.write_str(&format!("ExecutorEnum::RebuildEdgeIndex({})", exec.name())),
            ExecutorEnum::CreateSpace(exec) => f.write_str(&format!("ExecutorEnum::CreateSpace({})", exec.name())),
            ExecutorEnum::DropSpace(exec) => f.write_str(&format!("ExecutorEnum::DropSpace({})", exec.name())),
            ExecutorEnum::DescSpace(exec) => f.write_str(&format!("ExecutorEnum::DescSpace({})", exec.name())),
            ExecutorEnum::CreateTag(exec) => f.write_str(&format!("ExecutorEnum::CreateTag({})", exec.name())),
            ExecutorEnum::AlterTag(exec) => f.write_str(&format!("ExecutorEnum::AlterTag({})", exec.name())),
            ExecutorEnum::DescTag(exec) => f.write_str(&format!("ExecutorEnum::DescTag({})", exec.name())),
            ExecutorEnum::DropTag(exec) => f.write_str(&format!("ExecutorEnum::DropTag({})", exec.name())),
            ExecutorEnum::CreateEdge(exec) => f.write_str(&format!("ExecutorEnum::CreateEdge({})", exec.name())),
            ExecutorEnum::AlterEdge(exec) => f.write_str(&format!("ExecutorEnum::AlterEdge({})", exec.name())),
            ExecutorEnum::DescEdge(exec) => f.write_str(&format!("ExecutorEnum::DescEdge({})", exec.name())),
            ExecutorEnum::DropEdge(exec) => f.write_str(&format!("ExecutorEnum::DropEdge({})", exec.name())),
            ExecutorEnum::CreateUser(exec) => f.write_str(&format!("ExecutorEnum::CreateUser({})", exec.name())),
            ExecutorEnum::AlterUser(exec) => f.write_str(&format!("ExecutorEnum::AlterUser({})", exec.name())),
            ExecutorEnum::DropUser(exec) => f.write_str(&format!("ExecutorEnum::DropUser({})", exec.name())),
            ExecutorEnum::ChangePassword(exec) => f.write_str(&format!("ExecutorEnum::ChangePassword({})", exec.name())),
        }
    }
}

impl<S: StorageClient + Send + 'static> ExecutorEnum<S> {
    pub fn id(&self) -> i64 {
        match self {
            ExecutorEnum::Start(exec) => exec.id(),
            ExecutorEnum::Base(exec) => exec.id(),
            ExecutorEnum::GetVertices(exec) => exec.id(),
            ExecutorEnum::GetNeighbors(exec) => exec.id(),
            ExecutorEnum::GetProp(exec) => exec.id(),
            ExecutorEnum::AllPaths(exec) => exec.id(),
            ExecutorEnum::Expand(exec) => exec.id(),
            ExecutorEnum::ExpandAll(exec) => exec.id(),
            ExecutorEnum::Traverse(exec) => exec.id(),
            ExecutorEnum::ShortestPath(exec) => exec.id(),
            ExecutorEnum::MultiShortestPath(exec) => exec.id(),
            ExecutorEnum::InnerJoin(exec) => exec.id(),
            ExecutorEnum::HashInnerJoin(exec) => exec.id(),
            ExecutorEnum::LeftJoin(exec) => exec.id(),
            ExecutorEnum::HashLeftJoin(exec) => exec.id(),
            ExecutorEnum::CrossJoin(exec) => exec.id(),
            ExecutorEnum::Union(exec) => exec.id(),
            ExecutorEnum::UnionAll(exec) => exec.id(),
            ExecutorEnum::Minus(exec) => exec.id(),
            ExecutorEnum::Intersect(exec) => exec.id(),
            ExecutorEnum::Filter(exec) => exec.id(),
            ExecutorEnum::Project(exec) => exec.id(),
            ExecutorEnum::Limit(exec) => exec.id(),
            ExecutorEnum::Sort(exec) => exec.id(),
            ExecutorEnum::TopN(exec) => exec.id(),
            ExecutorEnum::Sample(exec) => exec.id(),
            ExecutorEnum::Aggregate(exec) => exec.id(),
            ExecutorEnum::GroupBy(exec) => exec.id(),
            ExecutorEnum::Having(exec) => exec.id(),
            ExecutorEnum::Dedup(exec) => exec.id(),
            ExecutorEnum::Unwind(exec) => exec.id(),
            ExecutorEnum::Assign(exec) => exec.id(),
            ExecutorEnum::AppendVertices(exec) => exec.id(),
            ExecutorEnum::RollUpApply(exec) => exec.id(),
            ExecutorEnum::PatternApply(exec) => exec.id(),
            ExecutorEnum::Loop(exec) => exec.id(),
            ExecutorEnum::ForLoop(exec) => exec.id(),
            ExecutorEnum::WhileLoop(exec) => exec.id(),
            ExecutorEnum::Select(exec) => exec.id(),
            ExecutorEnum::ScanEdges(exec) => exec.id(),
            ExecutorEnum::ScanVertices(exec) => exec.id(),
            ExecutorEnum::IndexScan(exec) => exec.id(),
            ExecutorEnum::Argument(exec) => exec.id(),
            ExecutorEnum::PassThrough(exec) => exec.id(),
            ExecutorEnum::DataCollect(exec) => exec.id(),
            ExecutorEnum::BFSShortest(exec) => exec.id(),
            ExecutorEnum::ShowSpaces(exec) => exec.id(),
            ExecutorEnum::ShowTags(exec) => exec.id(),
            ExecutorEnum::ShowEdges(exec) => exec.id(),
            ExecutorEnum::CreateTagIndex(exec) => exec.id(),
            ExecutorEnum::DropTagIndex(exec) => exec.id(),
            ExecutorEnum::DescTagIndex(exec) => exec.id(),
            ExecutorEnum::ShowTagIndexes(exec) => exec.id(),
            ExecutorEnum::RebuildTagIndex(exec) => exec.id(),
            ExecutorEnum::CreateEdgeIndex(exec) => exec.id(),
            ExecutorEnum::DropEdgeIndex(exec) => exec.id(),
            ExecutorEnum::DescEdgeIndex(exec) => exec.id(),
            ExecutorEnum::ShowEdgeIndexes(exec) => exec.id(),
            ExecutorEnum::RebuildEdgeIndex(exec) => exec.id(),
            ExecutorEnum::CreateSpace(exec) => exec.id(),
            ExecutorEnum::DropSpace(exec) => exec.id(),
            ExecutorEnum::DescSpace(exec) => exec.id(),
            ExecutorEnum::CreateTag(exec) => exec.id(),
            ExecutorEnum::AlterTag(exec) => exec.id(),
            ExecutorEnum::DescTag(exec) => exec.id(),
            ExecutorEnum::DropTag(exec) => exec.id(),
            ExecutorEnum::CreateEdge(exec) => exec.id(),
            ExecutorEnum::AlterEdge(exec) => exec.id(),
            ExecutorEnum::DescEdge(exec) => exec.id(),
            ExecutorEnum::DropEdge(exec) => exec.id(),
            ExecutorEnum::CreateUser(exec) => exec.id(),
            ExecutorEnum::AlterUser(exec) => exec.id(),
            ExecutorEnum::DropUser(exec) => exec.id(),
            ExecutorEnum::ChangePassword(exec) => exec.id(),
        }
    }

    pub fn name(&self) -> &str {
        match self {
            ExecutorEnum::Start(exec) => exec.name(),
            ExecutorEnum::Base(exec) => exec.name(),
            ExecutorEnum::GetVertices(exec) => exec.name(),
            ExecutorEnum::GetNeighbors(exec) => exec.name(),
            ExecutorEnum::GetProp(exec) => exec.name(),
            ExecutorEnum::AllPaths(exec) => exec.name(),
            ExecutorEnum::Expand(exec) => exec.name(),
            ExecutorEnum::ExpandAll(exec) => exec.name(),
            ExecutorEnum::Traverse(exec) => exec.name(),
            ExecutorEnum::ShortestPath(exec) => exec.name(),
            ExecutorEnum::MultiShortestPath(exec) => exec.name(),
            ExecutorEnum::InnerJoin(exec) => exec.name(),
            ExecutorEnum::HashInnerJoin(exec) => exec.name(),
            ExecutorEnum::LeftJoin(exec) => exec.name(),
            ExecutorEnum::HashLeftJoin(exec) => exec.name(),
            ExecutorEnum::CrossJoin(exec) => exec.name(),
            ExecutorEnum::Union(exec) => exec.name(),
            ExecutorEnum::UnionAll(exec) => exec.name(),
            ExecutorEnum::Minus(exec) => exec.name(),
            ExecutorEnum::Intersect(exec) => exec.name(),
            ExecutorEnum::Filter(exec) => exec.name(),
            ExecutorEnum::Project(exec) => exec.name(),
            ExecutorEnum::Limit(exec) => exec.name(),
            ExecutorEnum::Sort(exec) => exec.name(),
            ExecutorEnum::TopN(exec) => exec.name(),
            ExecutorEnum::Sample(exec) => exec.name(),
            ExecutorEnum::Aggregate(exec) => exec.name(),
            ExecutorEnum::GroupBy(exec) => exec.name(),
            ExecutorEnum::Having(exec) => exec.name(),
            ExecutorEnum::Dedup(exec) => exec.name(),
            ExecutorEnum::Unwind(exec) => exec.name(),
            ExecutorEnum::Assign(exec) => exec.name(),
            ExecutorEnum::AppendVertices(exec) => exec.name(),
            ExecutorEnum::RollUpApply(exec) => exec.name(),
            ExecutorEnum::PatternApply(exec) => exec.name(),
            ExecutorEnum::Loop(exec) => exec.name(),
            ExecutorEnum::ForLoop(exec) => exec.name(),
            ExecutorEnum::WhileLoop(exec) => exec.name(),
            ExecutorEnum::Select(exec) => exec.name(),
            ExecutorEnum::ScanEdges(exec) => exec.name(),
            ExecutorEnum::ScanVertices(exec) => exec.name(),
            ExecutorEnum::IndexScan(exec) => exec.name(),
            ExecutorEnum::Argument(exec) => exec.name(),
            ExecutorEnum::PassThrough(exec) => exec.name(),
            ExecutorEnum::DataCollect(exec) => exec.name(),
            ExecutorEnum::BFSShortest(exec) => exec.name(),
            ExecutorEnum::ShowSpaces(exec) => exec.name(),
            ExecutorEnum::ShowTags(exec) => exec.name(),
            ExecutorEnum::ShowEdges(exec) => exec.name(),
            ExecutorEnum::CreateTagIndex(exec) => exec.name(),
            ExecutorEnum::DropTagIndex(exec) => exec.name(),
            ExecutorEnum::DescTagIndex(exec) => exec.name(),
            ExecutorEnum::ShowTagIndexes(exec) => exec.name(),
            ExecutorEnum::RebuildTagIndex(exec) => exec.name(),
            ExecutorEnum::CreateEdgeIndex(exec) => exec.name(),
            ExecutorEnum::DropEdgeIndex(exec) => exec.name(),
            ExecutorEnum::DescEdgeIndex(exec) => exec.name(),
            ExecutorEnum::ShowEdgeIndexes(exec) => exec.name(),
            ExecutorEnum::RebuildEdgeIndex(exec) => exec.name(),
            ExecutorEnum::CreateSpace(exec) => exec.name(),
            ExecutorEnum::DropSpace(exec) => exec.name(),
            ExecutorEnum::DescSpace(exec) => exec.name(),
            ExecutorEnum::CreateTag(exec) => exec.name(),
            ExecutorEnum::AlterTag(exec) => exec.name(),
            ExecutorEnum::DescTag(exec) => exec.name(),
            ExecutorEnum::DropTag(exec) => exec.name(),
            ExecutorEnum::CreateEdge(exec) => exec.name(),
            ExecutorEnum::AlterEdge(exec) => exec.name(),
            ExecutorEnum::DescEdge(exec) => exec.name(),
            ExecutorEnum::DropEdge(exec) => exec.name(),
            ExecutorEnum::CreateUser(exec) => exec.name(),
            ExecutorEnum::AlterUser(exec) => exec.name(),
            ExecutorEnum::DropUser(exec) => exec.name(),
            ExecutorEnum::ChangePassword(exec) => exec.name(),
        }
    }

    pub fn stats(&self) -> &ExecutorStats {
        match self {
            ExecutorEnum::Start(exec) => exec.stats(),
            ExecutorEnum::Base(exec) => exec.stats(),
            ExecutorEnum::GetVertices(exec) => exec.stats(),
            ExecutorEnum::GetNeighbors(exec) => exec.stats(),
            ExecutorEnum::GetProp(exec) => exec.stats(),
            ExecutorEnum::AllPaths(exec) => exec.stats(),
            ExecutorEnum::Expand(exec) => exec.stats(),
            ExecutorEnum::ExpandAll(exec) => exec.stats(),
            ExecutorEnum::Traverse(exec) => exec.stats(),
            ExecutorEnum::ShortestPath(exec) => exec.stats(),
            ExecutorEnum::MultiShortestPath(exec) => exec.stats(),
            ExecutorEnum::InnerJoin(exec) => exec.stats(),
            ExecutorEnum::HashInnerJoin(exec) => exec.stats(),
            ExecutorEnum::LeftJoin(exec) => exec.stats(),
            ExecutorEnum::HashLeftJoin(exec) => exec.stats(),
            ExecutorEnum::CrossJoin(exec) => exec.stats(),
            ExecutorEnum::Union(exec) => exec.stats(),
            ExecutorEnum::UnionAll(exec) => exec.stats(),
            ExecutorEnum::Minus(exec) => exec.stats(),
            ExecutorEnum::Intersect(exec) => exec.stats(),
            ExecutorEnum::Filter(exec) => exec.stats(),
            ExecutorEnum::Project(exec) => exec.stats(),
            ExecutorEnum::Limit(exec) => exec.stats(),
            ExecutorEnum::Sort(exec) => exec.stats(),
            ExecutorEnum::TopN(exec) => exec.stats(),
            ExecutorEnum::Sample(exec) => exec.stats(),
            ExecutorEnum::Aggregate(exec) => exec.stats(),
            ExecutorEnum::GroupBy(exec) => exec.stats(),
            ExecutorEnum::Having(exec) => exec.stats(),
            ExecutorEnum::Dedup(exec) => exec.stats(),
            ExecutorEnum::Unwind(exec) => exec.stats(),
            ExecutorEnum::Assign(exec) => exec.stats(),
            ExecutorEnum::AppendVertices(exec) => exec.stats(),
            ExecutorEnum::RollUpApply(exec) => exec.stats(),
            ExecutorEnum::PatternApply(exec) => exec.stats(),
            ExecutorEnum::Loop(exec) => exec.stats(),
            ExecutorEnum::ForLoop(exec) => exec.stats(),
            ExecutorEnum::WhileLoop(exec) => exec.stats(),
            ExecutorEnum::Select(exec) => exec.stats(),
            ExecutorEnum::ScanEdges(exec) => exec.stats(),
            ExecutorEnum::ScanVertices(exec) => exec.stats(),
            ExecutorEnum::IndexScan(exec) => exec.stats(),
            ExecutorEnum::Argument(exec) => exec.stats(),
            ExecutorEnum::PassThrough(exec) => exec.stats(),
            ExecutorEnum::DataCollect(exec) => exec.stats(),
            ExecutorEnum::BFSShortest(exec) => exec.stats(),
            ExecutorEnum::ShowSpaces(exec) => exec.stats(),
            ExecutorEnum::ShowTags(exec) => exec.stats(),
            ExecutorEnum::ShowEdges(exec) => exec.stats(),
            ExecutorEnum::CreateTagIndex(exec) => exec.stats(),
            ExecutorEnum::DropTagIndex(exec) => exec.stats(),
            ExecutorEnum::DescTagIndex(exec) => exec.stats(),
            ExecutorEnum::ShowTagIndexes(exec) => exec.stats(),
            ExecutorEnum::RebuildTagIndex(exec) => exec.stats(),
            ExecutorEnum::CreateEdgeIndex(exec) => exec.stats(),
            ExecutorEnum::DropEdgeIndex(exec) => exec.stats(),
            ExecutorEnum::DescEdgeIndex(exec) => exec.stats(),
            ExecutorEnum::ShowEdgeIndexes(exec) => exec.stats(),
            ExecutorEnum::RebuildEdgeIndex(exec) => exec.stats(),
            ExecutorEnum::CreateSpace(exec) => exec.stats(),
            ExecutorEnum::DropSpace(exec) => exec.stats(),
            ExecutorEnum::DescSpace(exec) => exec.stats(),
            ExecutorEnum::CreateTag(exec) => exec.stats(),
            ExecutorEnum::AlterTag(exec) => exec.stats(),
            ExecutorEnum::DescTag(exec) => exec.stats(),
            ExecutorEnum::DropTag(exec) => exec.stats(),
            ExecutorEnum::CreateEdge(exec) => exec.stats(),
            ExecutorEnum::AlterEdge(exec) => exec.stats(),
            ExecutorEnum::DescEdge(exec) => exec.stats(),
            ExecutorEnum::DropEdge(exec) => exec.stats(),
            ExecutorEnum::CreateUser(exec) => exec.stats(),
            ExecutorEnum::AlterUser(exec) => exec.stats(),
            ExecutorEnum::DropUser(exec) => exec.stats(),
            ExecutorEnum::ChangePassword(exec) => exec.stats(),
        }
    }

    pub fn stats_mut(&mut self) -> &mut ExecutorStats {
        match self {
            ExecutorEnum::Start(exec) => exec.stats_mut(),
            ExecutorEnum::Base(exec) => exec.stats_mut(),
            ExecutorEnum::GetVertices(exec) => exec.stats_mut(),
            ExecutorEnum::GetNeighbors(exec) => exec.stats_mut(),
            ExecutorEnum::GetProp(exec) => exec.stats_mut(),
            ExecutorEnum::AllPaths(exec) => exec.stats_mut(),
            ExecutorEnum::Expand(exec) => exec.stats_mut(),
            ExecutorEnum::ExpandAll(exec) => exec.stats_mut(),
            ExecutorEnum::Traverse(exec) => exec.stats_mut(),
            ExecutorEnum::ShortestPath(exec) => exec.stats_mut(),
            ExecutorEnum::MultiShortestPath(exec) => exec.stats_mut(),
            ExecutorEnum::InnerJoin(exec) => exec.stats_mut(),
            ExecutorEnum::HashInnerJoin(exec) => exec.stats_mut(),
            ExecutorEnum::LeftJoin(exec) => exec.stats_mut(),
            ExecutorEnum::HashLeftJoin(exec) => exec.stats_mut(),
            ExecutorEnum::CrossJoin(exec) => exec.stats_mut(),
            ExecutorEnum::Union(exec) => exec.stats_mut(),
            ExecutorEnum::UnionAll(exec) => exec.stats_mut(),
            ExecutorEnum::Minus(exec) => exec.stats_mut(),
            ExecutorEnum::Intersect(exec) => exec.stats_mut(),
            ExecutorEnum::Filter(exec) => exec.stats_mut(),
            ExecutorEnum::Project(exec) => exec.stats_mut(),
            ExecutorEnum::Limit(exec) => exec.stats_mut(),
            ExecutorEnum::Sort(exec) => exec.stats_mut(),
            ExecutorEnum::TopN(exec) => exec.stats_mut(),
            ExecutorEnum::Sample(exec) => exec.stats_mut(),
            ExecutorEnum::Aggregate(exec) => exec.stats_mut(),
            ExecutorEnum::GroupBy(exec) => exec.stats_mut(),
            ExecutorEnum::Having(exec) => exec.stats_mut(),
            ExecutorEnum::Dedup(exec) => exec.stats_mut(),
            ExecutorEnum::Unwind(exec) => exec.stats_mut(),
            ExecutorEnum::Assign(exec) => exec.stats_mut(),
            ExecutorEnum::AppendVertices(exec) => exec.stats_mut(),
            ExecutorEnum::RollUpApply(exec) => exec.stats_mut(),
            ExecutorEnum::PatternApply(exec) => exec.stats_mut(),
            ExecutorEnum::Loop(exec) => exec.stats_mut(),
            ExecutorEnum::ForLoop(exec) => exec.stats_mut(),
            ExecutorEnum::WhileLoop(exec) => exec.stats_mut(),
            ExecutorEnum::Select(exec) => exec.stats_mut(),
            ExecutorEnum::ScanEdges(exec) => exec.stats_mut(),
            ExecutorEnum::ScanVertices(exec) => exec.stats_mut(),
            ExecutorEnum::IndexScan(exec) => exec.stats_mut(),
            ExecutorEnum::Argument(exec) => exec.stats_mut(),
            ExecutorEnum::PassThrough(exec) => exec.stats_mut(),
            ExecutorEnum::DataCollect(exec) => exec.stats_mut(),
            ExecutorEnum::BFSShortest(exec) => exec.stats_mut(),
            ExecutorEnum::ShowSpaces(exec) => exec.stats_mut(),
            ExecutorEnum::ShowTags(exec) => exec.stats_mut(),
            ExecutorEnum::ShowEdges(exec) => exec.stats_mut(),
            ExecutorEnum::CreateTagIndex(exec) => exec.stats_mut(),
            ExecutorEnum::DropTagIndex(exec) => exec.stats_mut(),
            ExecutorEnum::DescTagIndex(exec) => exec.stats_mut(),
            ExecutorEnum::ShowTagIndexes(exec) => exec.stats_mut(),
            ExecutorEnum::RebuildTagIndex(exec) => exec.stats_mut(),
            ExecutorEnum::CreateEdgeIndex(exec) => exec.stats_mut(),
            ExecutorEnum::DropEdgeIndex(exec) => exec.stats_mut(),
            ExecutorEnum::DescEdgeIndex(exec) => exec.stats_mut(),
            ExecutorEnum::ShowEdgeIndexes(exec) => exec.stats_mut(),
            ExecutorEnum::RebuildEdgeIndex(exec) => exec.stats_mut(),
            ExecutorEnum::CreateSpace(exec) => exec.stats_mut(),
            ExecutorEnum::DropSpace(exec) => exec.stats_mut(),
            ExecutorEnum::DescSpace(exec) => exec.stats_mut(),
            ExecutorEnum::CreateTag(exec) => exec.stats_mut(),
            ExecutorEnum::AlterTag(exec) => exec.stats_mut(),
            ExecutorEnum::DescTag(exec) => exec.stats_mut(),
            ExecutorEnum::DropTag(exec) => exec.stats_mut(),
            ExecutorEnum::CreateEdge(exec) => exec.stats_mut(),
            ExecutorEnum::AlterEdge(exec) => exec.stats_mut(),
            ExecutorEnum::DescEdge(exec) => exec.stats_mut(),
            ExecutorEnum::DropEdge(exec) => exec.stats_mut(),
            ExecutorEnum::CreateUser(exec) => exec.stats_mut(),
            ExecutorEnum::AlterUser(exec) => exec.stats_mut(),
            ExecutorEnum::DropUser(exec) => exec.stats_mut(),
            ExecutorEnum::ChangePassword(exec) => exec.stats_mut(),
        }
    }
}

impl<S: StorageClient + Send + 'static> super::base::Executor<S> for ExecutorEnum<S> {
    fn execute(&mut self) -> DBResult<ExecutionResult> {
        let start = Instant::now();
        let result = match self {
            ExecutorEnum::Start(exec) => exec.execute(),
            ExecutorEnum::Base(exec) => exec.execute(),
            ExecutorEnum::GetVertices(exec) => exec.execute(),
            ExecutorEnum::GetNeighbors(exec) => exec.execute(),
            ExecutorEnum::GetProp(exec) => exec.execute(),
            ExecutorEnum::AllPaths(exec) => exec.execute(),
            ExecutorEnum::Expand(exec) => exec.execute(),
            ExecutorEnum::ExpandAll(exec) => exec.execute(),
            ExecutorEnum::Traverse(exec) => exec.execute(),
            ExecutorEnum::ShortestPath(exec) => exec.execute(),
            ExecutorEnum::MultiShortestPath(exec) => exec.execute(),
            ExecutorEnum::InnerJoin(exec) => exec.execute(),
            ExecutorEnum::HashInnerJoin(exec) => exec.execute(),
            ExecutorEnum::LeftJoin(exec) => exec.execute(),
            ExecutorEnum::HashLeftJoin(exec) => exec.execute(),
            ExecutorEnum::CrossJoin(exec) => exec.execute(),
            ExecutorEnum::Union(exec) => exec.execute(),
            ExecutorEnum::UnionAll(exec) => exec.execute(),
            ExecutorEnum::Minus(exec) => exec.execute(),
            ExecutorEnum::Intersect(exec) => exec.execute(),
            ExecutorEnum::Filter(exec) => exec.execute(),
            ExecutorEnum::Project(exec) => exec.execute(),
            ExecutorEnum::Limit(exec) => exec.execute(),
            ExecutorEnum::Sort(exec) => exec.execute(),
            ExecutorEnum::TopN(exec) => exec.execute(),
            ExecutorEnum::Sample(exec) => exec.execute(),
            ExecutorEnum::Aggregate(exec) => exec.execute(),
            ExecutorEnum::GroupBy(exec) => exec.execute(),
            ExecutorEnum::Having(exec) => exec.execute(),
            ExecutorEnum::Dedup(exec) => exec.execute(),
            ExecutorEnum::Unwind(exec) => exec.execute(),
            ExecutorEnum::Assign(exec) => exec.execute(),
            ExecutorEnum::AppendVertices(exec) => exec.execute(),
            ExecutorEnum::RollUpApply(exec) => exec.execute(),
            ExecutorEnum::PatternApply(exec) => exec.execute(),
            ExecutorEnum::Loop(exec) => exec.execute(),
            ExecutorEnum::ForLoop(exec) => exec.execute(),
            ExecutorEnum::WhileLoop(exec) => exec.execute(),
            ExecutorEnum::Select(exec) => exec.execute(),
            ExecutorEnum::ScanEdges(exec) => exec.execute(),
            ExecutorEnum::ScanVertices(exec) => exec.execute(),
            ExecutorEnum::IndexScan(exec) => exec.execute(),
            ExecutorEnum::Argument(exec) => exec.execute(),
            ExecutorEnum::PassThrough(exec) => exec.execute(),
            ExecutorEnum::DataCollect(exec) => exec.execute(),
            ExecutorEnum::BFSShortest(exec) => exec.execute(),
            ExecutorEnum::ShowSpaces(exec) => exec.execute(),
            ExecutorEnum::ShowTags(exec) => exec.execute(),
            ExecutorEnum::ShowEdges(exec) => exec.execute(),
            ExecutorEnum::CreateTagIndex(exec) => exec.execute(),
            ExecutorEnum::DropTagIndex(exec) => exec.execute(),
            ExecutorEnum::DescTagIndex(exec) => exec.execute(),
            ExecutorEnum::ShowTagIndexes(exec) => exec.execute(),
            ExecutorEnum::RebuildTagIndex(exec) => exec.execute(),
            ExecutorEnum::CreateEdgeIndex(exec) => exec.execute(),
            ExecutorEnum::DropEdgeIndex(exec) => exec.execute(),
            ExecutorEnum::DescEdgeIndex(exec) => exec.execute(),
            ExecutorEnum::ShowEdgeIndexes(exec) => exec.execute(),
            ExecutorEnum::RebuildEdgeIndex(exec) => exec.execute(),
            ExecutorEnum::CreateSpace(exec) => exec.execute(),
            ExecutorEnum::DropSpace(exec) => exec.execute(),
            ExecutorEnum::DescSpace(exec) => exec.execute(),
            ExecutorEnum::CreateTag(exec) => exec.execute(),
            ExecutorEnum::AlterTag(exec) => exec.execute(),
            ExecutorEnum::DescTag(exec) => exec.execute(),
            ExecutorEnum::DropTag(exec) => exec.execute(),
            ExecutorEnum::CreateEdge(exec) => exec.execute(),
            ExecutorEnum::AlterEdge(exec) => exec.execute(),
            ExecutorEnum::DescEdge(exec) => exec.execute(),
            ExecutorEnum::DropEdge(exec) => exec.execute(),
            ExecutorEnum::CreateUser(exec) => exec.execute(),
            ExecutorEnum::AlterUser(exec) => exec.execute(),
            ExecutorEnum::DropUser(exec) => exec.execute(),
            ExecutorEnum::ChangePassword(exec) => exec.execute(),
        };
        self.stats_mut().add_total_time(start.elapsed());
        result
    }

    fn open(&mut self) -> DBResult<()> {
        match self {
            ExecutorEnum::Start(exec) => exec.open(),
            ExecutorEnum::Base(exec) => exec.open(),
            ExecutorEnum::GetVertices(exec) => exec.open(),
            ExecutorEnum::GetNeighbors(exec) => exec.open(),
            ExecutorEnum::GetProp(exec) => exec.open(),
            ExecutorEnum::AllPaths(exec) => exec.open(),
            ExecutorEnum::Expand(exec) => exec.open(),
            ExecutorEnum::ExpandAll(exec) => exec.open(),
            ExecutorEnum::Traverse(exec) => exec.open(),
            ExecutorEnum::ShortestPath(exec) => exec.open(),
            ExecutorEnum::MultiShortestPath(exec) => exec.open(),
            ExecutorEnum::InnerJoin(exec) => exec.open(),
            ExecutorEnum::HashInnerJoin(exec) => exec.open(),
            ExecutorEnum::LeftJoin(exec) => exec.open(),
            ExecutorEnum::HashLeftJoin(exec) => exec.open(),
            ExecutorEnum::CrossJoin(exec) => exec.open(),
            ExecutorEnum::Union(exec) => exec.open(),
            ExecutorEnum::UnionAll(exec) => exec.open(),
            ExecutorEnum::Minus(exec) => exec.open(),
            ExecutorEnum::Intersect(exec) => exec.open(),
            ExecutorEnum::Filter(exec) => exec.open(),
            ExecutorEnum::Project(exec) => exec.open(),
            ExecutorEnum::Limit(exec) => exec.open(),
            ExecutorEnum::Sort(exec) => exec.open(),
            ExecutorEnum::TopN(exec) => exec.open(),
            ExecutorEnum::Sample(exec) => exec.open(),
            ExecutorEnum::Aggregate(exec) => exec.open(),
            ExecutorEnum::GroupBy(exec) => exec.open(),
            ExecutorEnum::Having(exec) => exec.open(),
            ExecutorEnum::Dedup(exec) => exec.open(),
            ExecutorEnum::Unwind(exec) => exec.open(),
            ExecutorEnum::Assign(exec) => exec.open(),
            ExecutorEnum::AppendVertices(exec) => exec.open(),
            ExecutorEnum::RollUpApply(exec) => exec.open(),
            ExecutorEnum::PatternApply(exec) => exec.open(),
            ExecutorEnum::Loop(exec) => exec.open(),
            ExecutorEnum::ForLoop(exec) => exec.open(),
            ExecutorEnum::WhileLoop(exec) => exec.open(),
            ExecutorEnum::Select(exec) => exec.open(),
            ExecutorEnum::ScanEdges(exec) => exec.open(),
            ExecutorEnum::ScanVertices(exec) => exec.open(),
            ExecutorEnum::IndexScan(exec) => exec.open(),
            ExecutorEnum::Argument(exec) => exec.open(),
            ExecutorEnum::PassThrough(exec) => exec.open(),
            ExecutorEnum::DataCollect(exec) => exec.open(),
            ExecutorEnum::BFSShortest(exec) => exec.open(),
            ExecutorEnum::ShowSpaces(exec) => exec.open(),
            ExecutorEnum::ShowTags(exec) => exec.open(),
            ExecutorEnum::ShowEdges(exec) => exec.open(),
            ExecutorEnum::CreateTagIndex(exec) => exec.open(),
            ExecutorEnum::DropTagIndex(exec) => exec.open(),
            ExecutorEnum::DescTagIndex(exec) => exec.open(),
            ExecutorEnum::ShowTagIndexes(exec) => exec.open(),
            ExecutorEnum::RebuildTagIndex(exec) => exec.open(),
            ExecutorEnum::CreateEdgeIndex(exec) => exec.open(),
            ExecutorEnum::DropEdgeIndex(exec) => exec.open(),
            ExecutorEnum::DescEdgeIndex(exec) => exec.open(),
            ExecutorEnum::ShowEdgeIndexes(exec) => exec.open(),
            ExecutorEnum::RebuildEdgeIndex(exec) => exec.open(),
            ExecutorEnum::CreateSpace(exec) => exec.open(),
            ExecutorEnum::DropSpace(exec) => exec.open(),
            ExecutorEnum::DescSpace(exec) => exec.open(),
            ExecutorEnum::CreateTag(exec) => exec.open(),
            ExecutorEnum::AlterTag(exec) => exec.open(),
            ExecutorEnum::DescTag(exec) => exec.open(),
            ExecutorEnum::DropTag(exec) => exec.open(),
            ExecutorEnum::CreateEdge(exec) => exec.open(),
            ExecutorEnum::AlterEdge(exec) => exec.open(),
            ExecutorEnum::DescEdge(exec) => exec.open(),
            ExecutorEnum::DropEdge(exec) => exec.open(),
            ExecutorEnum::CreateUser(exec) => exec.open(),
            ExecutorEnum::AlterUser(exec) => exec.open(),
            ExecutorEnum::DropUser(exec) => exec.open(),
            ExecutorEnum::ChangePassword(exec) => exec.open(),
        }
    }

    fn close(&mut self) -> DBResult<()> {
        match self {
            ExecutorEnum::Start(exec) => exec.close(),
            ExecutorEnum::Base(exec) => exec.close(),
            ExecutorEnum::GetVertices(exec) => exec.close(),
            ExecutorEnum::GetNeighbors(exec) => exec.close(),
            ExecutorEnum::GetProp(exec) => exec.close(),
            ExecutorEnum::AllPaths(exec) => exec.close(),
            ExecutorEnum::Expand(exec) => exec.close(),
            ExecutorEnum::ExpandAll(exec) => exec.close(),
            ExecutorEnum::Traverse(exec) => exec.close(),
            ExecutorEnum::ShortestPath(exec) => exec.close(),
            ExecutorEnum::MultiShortestPath(exec) => exec.close(),
            ExecutorEnum::InnerJoin(exec) => exec.close(),
            ExecutorEnum::HashInnerJoin(exec) => exec.close(),
            ExecutorEnum::LeftJoin(exec) => exec.close(),
            ExecutorEnum::HashLeftJoin(exec) => exec.close(),
            ExecutorEnum::CrossJoin(exec) => exec.close(),
            ExecutorEnum::Union(exec) => exec.close(),
            ExecutorEnum::UnionAll(exec) => exec.close(),
            ExecutorEnum::Minus(exec) => exec.close(),
            ExecutorEnum::Intersect(exec) => exec.close(),
            ExecutorEnum::Filter(exec) => exec.close(),
            ExecutorEnum::Project(exec) => exec.close(),
            ExecutorEnum::Limit(exec) => exec.close(),
            ExecutorEnum::Sort(exec) => exec.close(),
            ExecutorEnum::TopN(exec) => exec.close(),
            ExecutorEnum::Sample(exec) => exec.close(),
            ExecutorEnum::Aggregate(exec) => exec.close(),
            ExecutorEnum::GroupBy(exec) => exec.close(),
            ExecutorEnum::Having(exec) => exec.close(),
            ExecutorEnum::Dedup(exec) => exec.close(),
            ExecutorEnum::Unwind(exec) => exec.close(),
            ExecutorEnum::Assign(exec) => exec.close(),
            ExecutorEnum::AppendVertices(exec) => exec.close(),
            ExecutorEnum::RollUpApply(exec) => exec.close(),
            ExecutorEnum::PatternApply(exec) => exec.close(),
            ExecutorEnum::Loop(exec) => exec.close(),
            ExecutorEnum::ForLoop(exec) => exec.close(),
            ExecutorEnum::WhileLoop(exec) => exec.close(),
            ExecutorEnum::Select(exec) => exec.close(),
            ExecutorEnum::ScanEdges(exec) => exec.close(),
            ExecutorEnum::ScanVertices(exec) => exec.close(),
            ExecutorEnum::IndexScan(exec) => exec.close(),
            ExecutorEnum::Argument(exec) => exec.close(),
            ExecutorEnum::PassThrough(exec) => exec.close(),
            ExecutorEnum::DataCollect(exec) => exec.close(),
            ExecutorEnum::BFSShortest(exec) => exec.close(),
            ExecutorEnum::ShowSpaces(exec) => exec.close(),
            ExecutorEnum::ShowTags(exec) => exec.close(),
            ExecutorEnum::ShowEdges(exec) => exec.close(),
            ExecutorEnum::CreateTagIndex(exec) => exec.close(),
            ExecutorEnum::DropTagIndex(exec) => exec.close(),
            ExecutorEnum::DescTagIndex(exec) => exec.close(),
            ExecutorEnum::ShowTagIndexes(exec) => exec.close(),
            ExecutorEnum::RebuildTagIndex(exec) => exec.close(),
            ExecutorEnum::CreateEdgeIndex(exec) => exec.close(),
            ExecutorEnum::DropEdgeIndex(exec) => exec.close(),
            ExecutorEnum::DescEdgeIndex(exec) => exec.close(),
            ExecutorEnum::ShowEdgeIndexes(exec) => exec.close(),
            ExecutorEnum::RebuildEdgeIndex(exec) => exec.close(),
            ExecutorEnum::CreateSpace(exec) => exec.close(),
            ExecutorEnum::DropSpace(exec) => exec.close(),
            ExecutorEnum::DescSpace(exec) => exec.close(),
            ExecutorEnum::CreateTag(exec) => exec.close(),
            ExecutorEnum::AlterTag(exec) => exec.close(),
            ExecutorEnum::DescTag(exec) => exec.close(),
            ExecutorEnum::DropTag(exec) => exec.close(),
            ExecutorEnum::CreateEdge(exec) => exec.close(),
            ExecutorEnum::AlterEdge(exec) => exec.close(),
            ExecutorEnum::DescEdge(exec) => exec.close(),
            ExecutorEnum::DropEdge(exec) => exec.close(),
            ExecutorEnum::CreateUser(exec) => exec.close(),
            ExecutorEnum::AlterUser(exec) => exec.close(),
            ExecutorEnum::DropUser(exec) => exec.close(),
            ExecutorEnum::ChangePassword(exec) => exec.close(),
        }
    }

    fn is_open(&self) -> bool {
        match self {
            ExecutorEnum::Start(exec) => exec.is_open(),
            ExecutorEnum::Base(exec) => exec.is_open(),
            ExecutorEnum::GetVertices(exec) => exec.is_open(),
            ExecutorEnum::GetNeighbors(exec) => exec.is_open(),
            ExecutorEnum::GetProp(exec) => exec.is_open(),
            ExecutorEnum::AllPaths(exec) => exec.is_open(),
            ExecutorEnum::Expand(exec) => exec.is_open(),
            ExecutorEnum::ExpandAll(exec) => exec.is_open(),
            ExecutorEnum::Traverse(exec) => exec.is_open(),
            ExecutorEnum::ShortestPath(exec) => exec.is_open(),
            ExecutorEnum::MultiShortestPath(exec) => exec.is_open(),
            ExecutorEnum::InnerJoin(exec) => exec.is_open(),
            ExecutorEnum::HashInnerJoin(exec) => exec.is_open(),
            ExecutorEnum::LeftJoin(exec) => exec.is_open(),
            ExecutorEnum::HashLeftJoin(exec) => exec.is_open(),
            ExecutorEnum::CrossJoin(exec) => exec.is_open(),
            ExecutorEnum::Union(exec) => exec.is_open(),
            ExecutorEnum::UnionAll(exec) => exec.is_open(),
            ExecutorEnum::Minus(exec) => exec.is_open(),
            ExecutorEnum::Intersect(exec) => exec.is_open(),
            ExecutorEnum::Filter(exec) => exec.is_open(),
            ExecutorEnum::Project(exec) => exec.is_open(),
            ExecutorEnum::Limit(exec) => exec.is_open(),
            ExecutorEnum::Sort(exec) => exec.is_open(),
            ExecutorEnum::TopN(exec) => exec.is_open(),
            ExecutorEnum::Sample(exec) => exec.is_open(),
            ExecutorEnum::Aggregate(exec) => exec.is_open(),
            ExecutorEnum::GroupBy(exec) => exec.is_open(),
            ExecutorEnum::Having(exec) => exec.is_open(),
            ExecutorEnum::Dedup(exec) => exec.is_open(),
            ExecutorEnum::Unwind(exec) => exec.is_open(),
            ExecutorEnum::Assign(exec) => exec.is_open(),
            ExecutorEnum::AppendVertices(exec) => exec.is_open(),
            ExecutorEnum::RollUpApply(exec) => exec.is_open(),
            ExecutorEnum::PatternApply(exec) => exec.is_open(),
            ExecutorEnum::Loop(exec) => exec.is_open(),
            ExecutorEnum::ForLoop(exec) => exec.is_open(),
            ExecutorEnum::WhileLoop(exec) => exec.is_open(),
            ExecutorEnum::Select(exec) => exec.is_open(),
            ExecutorEnum::ScanEdges(exec) => exec.is_open(),
            ExecutorEnum::ScanVertices(exec) => exec.is_open(),
            ExecutorEnum::IndexScan(exec) => exec.is_open(),
            ExecutorEnum::Argument(exec) => exec.is_open(),
            ExecutorEnum::PassThrough(exec) => exec.is_open(),
            ExecutorEnum::DataCollect(exec) => exec.is_open(),
            ExecutorEnum::BFSShortest(exec) => exec.is_open(),
            ExecutorEnum::ShowSpaces(exec) => exec.is_open(),
            ExecutorEnum::ShowTags(exec) => exec.is_open(),
            ExecutorEnum::ShowEdges(exec) => exec.is_open(),
            ExecutorEnum::CreateTagIndex(exec) => exec.is_open(),
            ExecutorEnum::DropTagIndex(exec) => exec.is_open(),
            ExecutorEnum::DescTagIndex(exec) => exec.is_open(),
            ExecutorEnum::ShowTagIndexes(exec) => exec.is_open(),
            ExecutorEnum::RebuildTagIndex(exec) => exec.is_open(),
            ExecutorEnum::CreateEdgeIndex(exec) => exec.is_open(),
            ExecutorEnum::DropEdgeIndex(exec) => exec.is_open(),
            ExecutorEnum::DescEdgeIndex(exec) => exec.is_open(),
            ExecutorEnum::ShowEdgeIndexes(exec) => exec.is_open(),
            ExecutorEnum::RebuildEdgeIndex(exec) => exec.is_open(),
            ExecutorEnum::CreateSpace(exec) => exec.is_open(),
            ExecutorEnum::DropSpace(exec) => exec.is_open(),
            ExecutorEnum::DescSpace(exec) => exec.is_open(),
            ExecutorEnum::CreateTag(exec) => exec.is_open(),
            ExecutorEnum::AlterTag(exec) => exec.is_open(),
            ExecutorEnum::DescTag(exec) => exec.is_open(),
            ExecutorEnum::DropTag(exec) => exec.is_open(),
            ExecutorEnum::CreateEdge(exec) => exec.is_open(),
            ExecutorEnum::AlterEdge(exec) => exec.is_open(),
            ExecutorEnum::DescEdge(exec) => exec.is_open(),
            ExecutorEnum::DropEdge(exec) => exec.is_open(),
            ExecutorEnum::CreateUser(exec) => exec.is_open(),
            ExecutorEnum::AlterUser(exec) => exec.is_open(),
            ExecutorEnum::DropUser(exec) => exec.is_open(),
            ExecutorEnum::ChangePassword(exec) => exec.is_open(),
        }
    }

    fn id(&self) -> i64 {
        self.id()
    }

    fn name(&self) -> &str {
        self.name()
    }

    fn description(&self) -> &str {
        self.name()
    }

    fn stats(&self) -> &ExecutorStats {
        match self {
            ExecutorEnum::Start(exec) => exec.stats(),
            ExecutorEnum::Base(exec) => exec.stats(),
            ExecutorEnum::GetVertices(exec) => exec.stats(),
            ExecutorEnum::GetNeighbors(exec) => exec.stats(),
            ExecutorEnum::GetProp(exec) => exec.stats(),
            ExecutorEnum::AllPaths(exec) => exec.stats(),
            ExecutorEnum::Expand(exec) => exec.stats(),
            ExecutorEnum::ExpandAll(exec) => exec.stats(),
            ExecutorEnum::Traverse(exec) => exec.stats(),
            ExecutorEnum::ShortestPath(exec) => exec.stats(),
            ExecutorEnum::MultiShortestPath(exec) => exec.stats(),
            ExecutorEnum::InnerJoin(exec) => exec.stats(),
            ExecutorEnum::HashInnerJoin(exec) => exec.stats(),
            ExecutorEnum::LeftJoin(exec) => exec.stats(),
            ExecutorEnum::HashLeftJoin(exec) => exec.stats(),
            ExecutorEnum::CrossJoin(exec) => exec.stats(),
            ExecutorEnum::Union(exec) => exec.stats(),
            ExecutorEnum::UnionAll(exec) => exec.stats(),
            ExecutorEnum::Minus(exec) => exec.stats(),
            ExecutorEnum::Intersect(exec) => exec.stats(),
            ExecutorEnum::Filter(exec) => exec.stats(),
            ExecutorEnum::Project(exec) => exec.stats(),
            ExecutorEnum::Limit(exec) => exec.stats(),
            ExecutorEnum::Sort(exec) => exec.stats(),
            ExecutorEnum::TopN(exec) => exec.stats(),
            ExecutorEnum::Sample(exec) => exec.stats(),
            ExecutorEnum::Aggregate(exec) => exec.stats(),
            ExecutorEnum::GroupBy(exec) => exec.stats(),
            ExecutorEnum::Having(exec) => exec.stats(),
            ExecutorEnum::Dedup(exec) => exec.stats(),
            ExecutorEnum::Unwind(exec) => exec.stats(),
            ExecutorEnum::Assign(exec) => exec.stats(),
            ExecutorEnum::AppendVertices(exec) => exec.stats(),
            ExecutorEnum::RollUpApply(exec) => exec.stats(),
            ExecutorEnum::PatternApply(exec) => exec.stats(),
            ExecutorEnum::Loop(exec) => exec.stats(),
            ExecutorEnum::ForLoop(exec) => exec.stats(),
            ExecutorEnum::WhileLoop(exec) => exec.stats(),
            ExecutorEnum::Select(exec) => exec.stats(),
            ExecutorEnum::ScanEdges(exec) => exec.stats(),
            ExecutorEnum::ScanVertices(exec) => exec.stats(),
            ExecutorEnum::IndexScan(exec) => exec.stats(),
            ExecutorEnum::Argument(exec) => exec.stats(),
            ExecutorEnum::PassThrough(exec) => exec.stats(),
            ExecutorEnum::DataCollect(exec) => exec.stats(),
            ExecutorEnum::BFSShortest(exec) => exec.stats(),
            ExecutorEnum::ShowSpaces(exec) => exec.stats(),
            ExecutorEnum::ShowTags(exec) => exec.stats(),
            ExecutorEnum::ShowEdges(exec) => exec.stats(),
            ExecutorEnum::CreateTagIndex(exec) => exec.stats(),
            ExecutorEnum::DropTagIndex(exec) => exec.stats(),
            ExecutorEnum::DescTagIndex(exec) => exec.stats(),
            ExecutorEnum::ShowTagIndexes(exec) => exec.stats(),
            ExecutorEnum::RebuildTagIndex(exec) => exec.stats(),
            ExecutorEnum::CreateEdgeIndex(exec) => exec.stats(),
            ExecutorEnum::DropEdgeIndex(exec) => exec.stats(),
            ExecutorEnum::DescEdgeIndex(exec) => exec.stats(),
            ExecutorEnum::ShowEdgeIndexes(exec) => exec.stats(),
            ExecutorEnum::RebuildEdgeIndex(exec) => exec.stats(),
            ExecutorEnum::CreateSpace(exec) => exec.stats(),
            ExecutorEnum::DropSpace(exec) => exec.stats(),
            ExecutorEnum::DescSpace(exec) => exec.stats(),
            ExecutorEnum::CreateTag(exec) => exec.stats(),
            ExecutorEnum::AlterTag(exec) => exec.stats(),
            ExecutorEnum::DescTag(exec) => exec.stats(),
            ExecutorEnum::DropTag(exec) => exec.stats(),
            ExecutorEnum::CreateEdge(exec) => exec.stats(),
            ExecutorEnum::AlterEdge(exec) => exec.stats(),
            ExecutorEnum::DescEdge(exec) => exec.stats(),
            ExecutorEnum::DropEdge(exec) => exec.stats(),
            ExecutorEnum::CreateUser(exec) => exec.stats(),
            ExecutorEnum::AlterUser(exec) => exec.stats(),
            ExecutorEnum::DropUser(exec) => exec.stats(),
            ExecutorEnum::ChangePassword(exec) => exec.stats(),
        }
    }

    fn stats_mut(&mut self) -> &mut ExecutorStats {
        match self {
            ExecutorEnum::Start(exec) => exec.stats_mut(),
            ExecutorEnum::Base(exec) => exec.stats_mut(),
            ExecutorEnum::GetVertices(exec) => exec.stats_mut(),
            ExecutorEnum::GetNeighbors(exec) => exec.stats_mut(),
            ExecutorEnum::GetProp(exec) => exec.stats_mut(),
            ExecutorEnum::AllPaths(exec) => exec.stats_mut(),
            ExecutorEnum::Expand(exec) => exec.stats_mut(),
            ExecutorEnum::ExpandAll(exec) => exec.stats_mut(),
            ExecutorEnum::Traverse(exec) => exec.stats_mut(),
            ExecutorEnum::ShortestPath(exec) => exec.stats_mut(),
            ExecutorEnum::MultiShortestPath(exec) => exec.stats_mut(),
            ExecutorEnum::InnerJoin(exec) => exec.stats_mut(),
            ExecutorEnum::HashInnerJoin(exec) => exec.stats_mut(),
            ExecutorEnum::LeftJoin(exec) => exec.stats_mut(),
            ExecutorEnum::HashLeftJoin(exec) => exec.stats_mut(),
            ExecutorEnum::CrossJoin(exec) => exec.stats_mut(),
            ExecutorEnum::Union(exec) => exec.stats_mut(),
            ExecutorEnum::UnionAll(exec) => exec.stats_mut(),
            ExecutorEnum::Minus(exec) => exec.stats_mut(),
            ExecutorEnum::Intersect(exec) => exec.stats_mut(),
            ExecutorEnum::Filter(exec) => exec.stats_mut(),
            ExecutorEnum::Project(exec) => exec.stats_mut(),
            ExecutorEnum::Limit(exec) => exec.stats_mut(),
            ExecutorEnum::Sort(exec) => exec.stats_mut(),
            ExecutorEnum::TopN(exec) => exec.stats_mut(),
            ExecutorEnum::Sample(exec) => exec.stats_mut(),
            ExecutorEnum::Aggregate(exec) => exec.stats_mut(),
            ExecutorEnum::GroupBy(exec) => exec.stats_mut(),
            ExecutorEnum::Having(exec) => exec.stats_mut(),
            ExecutorEnum::Dedup(exec) => exec.stats_mut(),
            ExecutorEnum::Unwind(exec) => exec.stats_mut(),
            ExecutorEnum::Assign(exec) => exec.stats_mut(),
            ExecutorEnum::AppendVertices(exec) => exec.stats_mut(),
            ExecutorEnum::RollUpApply(exec) => exec.stats_mut(),
            ExecutorEnum::PatternApply(exec) => exec.stats_mut(),
            ExecutorEnum::Loop(exec) => exec.stats_mut(),
            ExecutorEnum::ForLoop(exec) => exec.stats_mut(),
            ExecutorEnum::WhileLoop(exec) => exec.stats_mut(),
            ExecutorEnum::Select(exec) => exec.stats_mut(),
            ExecutorEnum::ScanEdges(exec) => exec.stats_mut(),
            ExecutorEnum::ScanVertices(exec) => exec.stats_mut(),
            ExecutorEnum::IndexScan(exec) => exec.stats_mut(),
            ExecutorEnum::Argument(exec) => exec.stats_mut(),
            ExecutorEnum::PassThrough(exec) => exec.stats_mut(),
            ExecutorEnum::DataCollect(exec) => exec.stats_mut(),
            ExecutorEnum::BFSShortest(exec) => exec.stats_mut(),
            ExecutorEnum::ShowSpaces(exec) => exec.stats_mut(),
            ExecutorEnum::ShowTags(exec) => exec.stats_mut(),
            ExecutorEnum::ShowEdges(exec) => exec.stats_mut(),
            ExecutorEnum::CreateTagIndex(exec) => exec.stats_mut(),
            ExecutorEnum::DropTagIndex(exec) => exec.stats_mut(),
            ExecutorEnum::DescTagIndex(exec) => exec.stats_mut(),
            ExecutorEnum::ShowTagIndexes(exec) => exec.stats_mut(),
            ExecutorEnum::RebuildTagIndex(exec) => exec.stats_mut(),
            ExecutorEnum::CreateEdgeIndex(exec) => exec.stats_mut(),
            ExecutorEnum::DropEdgeIndex(exec) => exec.stats_mut(),
            ExecutorEnum::DescEdgeIndex(exec) => exec.stats_mut(),
            ExecutorEnum::ShowEdgeIndexes(exec) => exec.stats_mut(),
            ExecutorEnum::RebuildEdgeIndex(exec) => exec.stats_mut(),
            ExecutorEnum::CreateSpace(exec) => exec.stats_mut(),
            ExecutorEnum::DropSpace(exec) => exec.stats_mut(),
            ExecutorEnum::DescSpace(exec) => exec.stats_mut(),
            ExecutorEnum::CreateTag(exec) => exec.stats_mut(),
            ExecutorEnum::AlterTag(exec) => exec.stats_mut(),
            ExecutorEnum::DescTag(exec) => exec.stats_mut(),
            ExecutorEnum::DropTag(exec) => exec.stats_mut(),
            ExecutorEnum::CreateEdge(exec) => exec.stats_mut(),
            ExecutorEnum::AlterEdge(exec) => exec.stats_mut(),
            ExecutorEnum::DescEdge(exec) => exec.stats_mut(),
            ExecutorEnum::DropEdge(exec) => exec.stats_mut(),
            ExecutorEnum::CreateUser(exec) => exec.stats_mut(),
            ExecutorEnum::AlterUser(exec) => exec.stats_mut(),
            ExecutorEnum::DropUser(exec) => exec.stats_mut(),
            ExecutorEnum::ChangePassword(exec) => exec.stats_mut(),
        }
    }
}

impl<S: StorageClient + Send + 'static> InputExecutor<S> for ExecutorEnum<S> {
    fn set_input(&mut self, input: ExecutorEnum<S>) {
        match self {
            ExecutorEnum::Filter(exec) => exec.set_input(input),
            ExecutorEnum::Project(exec) => exec.set_input(input),
            ExecutorEnum::Limit(exec) => exec.set_input(input),
            ExecutorEnum::Sort(exec) => exec.set_input(input),
            ExecutorEnum::TopN(exec) => exec.set_input(input),
            ExecutorEnum::Sample(exec) => exec.set_input(input),
            ExecutorEnum::Dedup(exec) => exec.set_input(input),
            ExecutorEnum::Expand(exec) => exec.set_input(input),
            ExecutorEnum::ExpandAll(exec) => exec.set_input(input),
            ExecutorEnum::Traverse(exec) => exec.set_input(input),
            ExecutorEnum::ShortestPath(exec) => exec.set_input(input),
            ExecutorEnum::MultiShortestPath(exec) => exec.set_input(input),
            ExecutorEnum::Aggregate(exec) => exec.set_input(input),
            ExecutorEnum::GroupBy(exec) => exec.set_input(input),
            ExecutorEnum::Having(exec) => exec.set_input(input),
            ExecutorEnum::Unwind(_) => {}
            ExecutorEnum::Assign(_) => {}
            ExecutorEnum::AppendVertices(_) => {}
            ExecutorEnum::PatternApply(_) => {}
            ExecutorEnum::RollUpApply(_) => {}
            ExecutorEnum::Loop(_) => {}
            ExecutorEnum::ForLoop(_) => {}
            ExecutorEnum::WhileLoop(_) => {}
            ExecutorEnum::Select(_) => {}
            ExecutorEnum::ScanEdges(_) => {}
            ExecutorEnum::ScanVertices(_) => {}
            ExecutorEnum::IndexScan(_) => {}
            ExecutorEnum::Argument(_) => {}
            ExecutorEnum::PassThrough(_) => {}
            ExecutorEnum::DataCollect(_) => {}
            ExecutorEnum::BFSShortest(_) => {}
            ExecutorEnum::ShowSpaces(_) => {}
            ExecutorEnum::ShowTags(_) => {}
            ExecutorEnum::ShowEdges(_) => {}
            ExecutorEnum::CreateTagIndex(_) => {}
            ExecutorEnum::DropTagIndex(_) => {}
            ExecutorEnum::DescTagIndex(_) => {}
            ExecutorEnum::ShowTagIndexes(_) => {}
            ExecutorEnum::RebuildTagIndex(_) => {}
            ExecutorEnum::CreateEdgeIndex(_) => {}
            ExecutorEnum::DropEdgeIndex(_) => {}
            ExecutorEnum::DescEdgeIndex(_) => {}
            ExecutorEnum::ShowEdgeIndexes(_) => {}
            ExecutorEnum::RebuildEdgeIndex(_) => {}
            ExecutorEnum::InnerJoin(_) => {}
            ExecutorEnum::HashInnerJoin(_) => {}
            ExecutorEnum::LeftJoin(_) => {}
            ExecutorEnum::HashLeftJoin(_) => {}
            ExecutorEnum::CrossJoin(_) => {}
            ExecutorEnum::Start(_) => {}
            ExecutorEnum::Base(_) => {}
            ExecutorEnum::GetVertices(_) => {}
            ExecutorEnum::GetNeighbors(_) => {}
            ExecutorEnum::GetProp(_) => {}
            ExecutorEnum::AllPaths(_) => {}
            ExecutorEnum::Union(_) => {}
            ExecutorEnum::UnionAll(_) => {}
            ExecutorEnum::Minus(_) => {}
            ExecutorEnum::Intersect(_) => {}
            ExecutorEnum::CreateSpace(_) => {}
            ExecutorEnum::DropSpace(_) => {}
            ExecutorEnum::DescSpace(_) => {}
            ExecutorEnum::CreateTag(_) => {}
            ExecutorEnum::AlterTag(_) => {}
            ExecutorEnum::DescTag(_) => {}
            ExecutorEnum::DropTag(_) => {}
            ExecutorEnum::CreateEdge(_) => {}
            ExecutorEnum::AlterEdge(_) => {}
            ExecutorEnum::DescEdge(_) => {}
            ExecutorEnum::DropEdge(_) => {}
            ExecutorEnum::CreateUser(_) => {}
            ExecutorEnum::AlterUser(_) => {}
            ExecutorEnum::DropUser(_) => {}
            ExecutorEnum::ChangePassword(_) => {}
        }
    }

    fn get_input(&self) -> Option<&ExecutorEnum<S>> {
        match self {
            ExecutorEnum::Filter(exec) => exec.get_input(),
            ExecutorEnum::Project(exec) => exec.get_input(),
            ExecutorEnum::Limit(exec) => exec.get_input(),
            ExecutorEnum::Sort(exec) => exec.get_input(),
            ExecutorEnum::TopN(exec) => exec.get_input(),
            ExecutorEnum::Sample(exec) => exec.get_input(),
            ExecutorEnum::Dedup(exec) => exec.get_input(),
            ExecutorEnum::Expand(exec) => exec.get_input(),
            ExecutorEnum::ExpandAll(exec) => exec.get_input(),
            ExecutorEnum::Traverse(exec) => exec.get_input(),
            ExecutorEnum::ShortestPath(exec) => exec.get_input(),
            ExecutorEnum::MultiShortestPath(exec) => exec.get_input(),
            ExecutorEnum::Aggregate(exec) => exec.get_input(),
            ExecutorEnum::GroupBy(exec) => exec.get_input(),
            ExecutorEnum::Having(exec) => exec.get_input(),
            ExecutorEnum::Unwind(_) => None,
            ExecutorEnum::Assign(_) => None,
            ExecutorEnum::AppendVertices(_) => None,
            ExecutorEnum::PatternApply(_) => None,
            ExecutorEnum::RollUpApply(_) => None,
            ExecutorEnum::Loop(_) => None,
            ExecutorEnum::ForLoop(_) => None,
            ExecutorEnum::WhileLoop(_) => None,
            ExecutorEnum::Select(_) => None,
            ExecutorEnum::ScanEdges(_) => None,
            ExecutorEnum::ScanVertices(_) => None,
            ExecutorEnum::IndexScan(_) => None,
            ExecutorEnum::Argument(_) => None,
            ExecutorEnum::PassThrough(_) => None,
            ExecutorEnum::DataCollect(_) => None,
            ExecutorEnum::BFSShortest(_) => None,
            ExecutorEnum::ShowSpaces(_) => None,
            ExecutorEnum::ShowTags(_) => None,
            ExecutorEnum::ShowEdges(_) => None,
            ExecutorEnum::CreateTagIndex(_) => None,
            ExecutorEnum::DropTagIndex(_) => None,
            ExecutorEnum::DescTagIndex(_) => None,
            ExecutorEnum::ShowTagIndexes(_) => None,
            ExecutorEnum::RebuildTagIndex(_) => None,
            ExecutorEnum::CreateEdgeIndex(_) => None,
            ExecutorEnum::DropEdgeIndex(_) => None,
            ExecutorEnum::DescEdgeIndex(_) => None,
            ExecutorEnum::ShowEdgeIndexes(_) => None,
            ExecutorEnum::RebuildEdgeIndex(_) => None,
            ExecutorEnum::InnerJoin(_) => None,
            ExecutorEnum::HashInnerJoin(_) => None,
            ExecutorEnum::LeftJoin(_) => None,
            ExecutorEnum::HashLeftJoin(_) => None,
            ExecutorEnum::CrossJoin(_) => None,
            ExecutorEnum::Start(_) => None,
            ExecutorEnum::Base(_) => None,
            ExecutorEnum::GetVertices(_) => None,
            ExecutorEnum::GetNeighbors(_) => None,
            ExecutorEnum::GetProp(_) => None,
            ExecutorEnum::AllPaths(_) => None,
            ExecutorEnum::Union(_) => None,
            ExecutorEnum::UnionAll(_) => None,
            ExecutorEnum::Minus(_) => None,
            ExecutorEnum::Intersect(_) => None,
            ExecutorEnum::CreateSpace(_) => None,
            ExecutorEnum::DropSpace(_) => None,
            ExecutorEnum::DescSpace(_) => None,
            ExecutorEnum::CreateTag(_) => None,
            ExecutorEnum::AlterTag(_) => None,
            ExecutorEnum::DescTag(_) => None,
            ExecutorEnum::DropTag(_) => None,
            ExecutorEnum::CreateEdge(_) => None,
            ExecutorEnum::AlterEdge(_) => None,
            ExecutorEnum::DescEdge(_) => None,
            ExecutorEnum::DropEdge(_) => None,
            ExecutorEnum::CreateUser(_) => None,
            ExecutorEnum::AlterUser(_) => None,
            ExecutorEnum::DropUser(_) => None,
            ExecutorEnum::ChangePassword(_) => None,
        }
    }
}

pub trait ChainableExecutor<S: StorageClient + Send + 'static>:
    super::base::Executor<S> + InputExecutor<S>
{
    fn into_executor_enum(self) -> ExecutorEnum<S>
    where
        Self: Sized + 'static;
}

impl<S: StorageClient + Send + 'static> ChainableExecutor<S> for ExecutorEnum<S> {
    fn into_executor_enum(self) -> ExecutorEnum<S> {
        self
    }
}

use crate::query::core::{NodeType, NodeCategory};

/// ExecutorEnum 的 NodeType trait 实现
///
/// 为每个执行器变体提供统一的类型标识和分类
impl<S: StorageClient + Send + 'static> NodeType for ExecutorEnum<S> {
    fn node_type_id(&self) -> &'static str {
        match self {
            ExecutorEnum::Start(_) => "start",
            ExecutorEnum::Base(_) => "base",
            ExecutorEnum::GetVertices(_) => "get_vertices",
            ExecutorEnum::GetNeighbors(_) => "get_neighbors",
            ExecutorEnum::GetProp(_) => "get_prop",
            ExecutorEnum::AllPaths(_) => "all_paths",
            ExecutorEnum::Expand(_) => "expand",
            ExecutorEnum::ExpandAll(_) => "expand_all",
            ExecutorEnum::Traverse(_) => "traverse",
            ExecutorEnum::ShortestPath(_) => "shortest_path",
            ExecutorEnum::MultiShortestPath(_) => "multi_shortest_path",
            ExecutorEnum::InnerJoin(_) => "inner_join",
            ExecutorEnum::HashInnerJoin(_) => "hash_inner_join",
            ExecutorEnum::LeftJoin(_) => "left_join",
            ExecutorEnum::HashLeftJoin(_) => "hash_left_join",
            ExecutorEnum::CrossJoin(_) => "cross_join",
            ExecutorEnum::Union(_) => "union",
            ExecutorEnum::UnionAll(_) => "union_all",
            ExecutorEnum::Minus(_) => "minus",
            ExecutorEnum::Intersect(_) => "intersect",
            ExecutorEnum::Filter(_) => "filter",
            ExecutorEnum::Project(_) => "project",
            ExecutorEnum::Limit(_) => "limit",
            ExecutorEnum::Sort(_) => "sort",
            ExecutorEnum::TopN(_) => "topn",
            ExecutorEnum::Sample(_) => "sample",
            ExecutorEnum::Aggregate(_) => "aggregate",
            ExecutorEnum::GroupBy(_) => "group_by",
            ExecutorEnum::Having(_) => "having",
            ExecutorEnum::Dedup(_) => "dedup",
            ExecutorEnum::Unwind(_) => "unwind",
            ExecutorEnum::Assign(_) => "assign",
            ExecutorEnum::AppendVertices(_) => "append_vertices",
            ExecutorEnum::RollUpApply(_) => "rollup_apply",
            ExecutorEnum::PatternApply(_) => "pattern_apply",
            ExecutorEnum::Loop(_) => "loop",
            ExecutorEnum::ForLoop(_) => "for_loop",
            ExecutorEnum::WhileLoop(_) => "while_loop",
            ExecutorEnum::Select(_) => "select",
            ExecutorEnum::ScanEdges(_) => "scan_edges",
            ExecutorEnum::ScanVertices(_) => "scan_vertices",
            ExecutorEnum::IndexScan(_) => "index_scan",
            ExecutorEnum::Argument(_) => "argument",
            ExecutorEnum::PassThrough(_) => "pass_through",
            ExecutorEnum::DataCollect(_) => "data_collect",
            ExecutorEnum::BFSShortest(_) => "bfs_shortest",
            ExecutorEnum::ShowSpaces(_) => "show_spaces",
            ExecutorEnum::ShowTags(_) => "show_tags",
            ExecutorEnum::ShowEdges(_) => "show_edges",
            ExecutorEnum::CreateTagIndex(_) => "create_tag_index",
            ExecutorEnum::DropTagIndex(_) => "drop_tag_index",
            ExecutorEnum::DescTagIndex(_) => "desc_tag_index",
            ExecutorEnum::ShowTagIndexes(_) => "show_tag_indexes",
            ExecutorEnum::RebuildTagIndex(_) => "rebuild_tag_index",
            ExecutorEnum::CreateEdgeIndex(_) => "create_edge_index",
            ExecutorEnum::DropEdgeIndex(_) => "drop_edge_index",
            ExecutorEnum::DescEdgeIndex(_) => "desc_edge_index",
            ExecutorEnum::ShowEdgeIndexes(_) => "show_edge_indexes",
            ExecutorEnum::RebuildEdgeIndex(_) => "rebuild_edge_index",
            ExecutorEnum::CreateSpace(_) => "create_space",
            ExecutorEnum::DropSpace(_) => "drop_space",
            ExecutorEnum::DescSpace(_) => "desc_space",
            ExecutorEnum::CreateTag(_) => "create_tag",
            ExecutorEnum::AlterTag(_) => "alter_tag",
            ExecutorEnum::DescTag(_) => "desc_tag",
            ExecutorEnum::DropTag(_) => "drop_tag",
            ExecutorEnum::CreateEdge(_) => "create_edge",
            ExecutorEnum::AlterEdge(_) => "alter_edge",
            ExecutorEnum::DescEdge(_) => "desc_edge",
            ExecutorEnum::DropEdge(_) => "drop_edge",
            ExecutorEnum::CreateUser(_) => "create_user",
            ExecutorEnum::AlterUser(_) => "alter_user",
            ExecutorEnum::DropUser(_) => "drop_user",
            ExecutorEnum::ChangePassword(_) => "change_password",
        }
    }

    fn node_type_name(&self) -> &'static str {
        match self {
            ExecutorEnum::Start(_) => "Start",
            ExecutorEnum::Base(_) => "Base",
            ExecutorEnum::GetVertices(_) => "Get Vertices",
            ExecutorEnum::GetNeighbors(_) => "Get Neighbors",
            ExecutorEnum::GetProp(_) => "Get Prop",
            ExecutorEnum::AllPaths(_) => "All Paths",
            ExecutorEnum::Expand(_) => "Expand",
            ExecutorEnum::ExpandAll(_) => "Expand All",
            ExecutorEnum::Traverse(_) => "Traverse",
            ExecutorEnum::ShortestPath(_) => "Shortest Path",
            ExecutorEnum::MultiShortestPath(_) => "Multi Shortest Path",
            ExecutorEnum::InnerJoin(_) => "Inner Join",
            ExecutorEnum::HashInnerJoin(_) => "Hash Inner Join",
            ExecutorEnum::LeftJoin(_) => "Left Join",
            ExecutorEnum::HashLeftJoin(_) => "Hash Left Join",
            ExecutorEnum::CrossJoin(_) => "Cross Join",
            ExecutorEnum::Union(_) => "Union",
            ExecutorEnum::UnionAll(_) => "Union All",
            ExecutorEnum::Minus(_) => "Minus",
            ExecutorEnum::Intersect(_) => "Intersect",
            ExecutorEnum::Filter(_) => "Filter",
            ExecutorEnum::Project(_) => "Project",
            ExecutorEnum::Limit(_) => "Limit",
            ExecutorEnum::Sort(_) => "Sort",
            ExecutorEnum::TopN(_) => "TopN",
            ExecutorEnum::Sample(_) => "Sample",
            ExecutorEnum::Aggregate(_) => "Aggregate",
            ExecutorEnum::GroupBy(_) => "Group By",
            ExecutorEnum::Having(_) => "Having",
            ExecutorEnum::Dedup(_) => "Dedup",
            ExecutorEnum::Unwind(_) => "Unwind",
            ExecutorEnum::Assign(_) => "Assign",
            ExecutorEnum::AppendVertices(_) => "Append Vertices",
            ExecutorEnum::RollUpApply(_) => "RollUp Apply",
            ExecutorEnum::PatternApply(_) => "Pattern Apply",
            ExecutorEnum::Loop(_) => "Loop",
            ExecutorEnum::ForLoop(_) => "For Loop",
            ExecutorEnum::WhileLoop(_) => "While Loop",
            ExecutorEnum::Select(_) => "Select",
            ExecutorEnum::ScanEdges(_) => "Scan Edges",
            ExecutorEnum::ScanVertices(_) => "Scan Vertices",
            ExecutorEnum::IndexScan(_) => "Index Scan",
            ExecutorEnum::Argument(_) => "Argument",
            ExecutorEnum::PassThrough(_) => "Pass Through",
            ExecutorEnum::DataCollect(_) => "Data Collect",
            ExecutorEnum::BFSShortest(_) => "BFS Shortest",
            ExecutorEnum::ShowSpaces(_) => "Show Spaces",
            ExecutorEnum::ShowTags(_) => "Show Tags",
            ExecutorEnum::ShowEdges(_) => "Show Edges",
            ExecutorEnum::CreateTagIndex(_) => "Create Tag Index",
            ExecutorEnum::DropTagIndex(_) => "Drop Tag Index",
            ExecutorEnum::DescTagIndex(_) => "Describe Tag Index",
            ExecutorEnum::ShowTagIndexes(_) => "Show Tag Indexes",
            ExecutorEnum::RebuildTagIndex(_) => "Rebuild Tag Index",
            ExecutorEnum::CreateEdgeIndex(_) => "Create Edge Index",
            ExecutorEnum::DropEdgeIndex(_) => "Drop Edge Index",
            ExecutorEnum::DescEdgeIndex(_) => "Describe Edge Index",
            ExecutorEnum::ShowEdgeIndexes(_) => "Show Edge Indexes",
            ExecutorEnum::RebuildEdgeIndex(_) => "Rebuild Edge Index",
            ExecutorEnum::CreateSpace(_) => "Create Space",
            ExecutorEnum::DropSpace(_) => "Drop Space",
            ExecutorEnum::DescSpace(_) => "Describe Space",
            ExecutorEnum::CreateTag(_) => "Create Tag",
            ExecutorEnum::AlterTag(_) => "Alter Tag",
            ExecutorEnum::DescTag(_) => "Describe Tag",
            ExecutorEnum::DropTag(_) => "Drop Tag",
            ExecutorEnum::CreateEdge(_) => "Create Edge",
            ExecutorEnum::AlterEdge(_) => "Alter Edge",
            ExecutorEnum::DescEdge(_) => "Describe Edge",
            ExecutorEnum::DropEdge(_) => "Drop Edge",
            ExecutorEnum::CreateUser(_) => "Create User",
            ExecutorEnum::AlterUser(_) => "Alter User",
            ExecutorEnum::DropUser(_) => "Drop User",
            ExecutorEnum::ChangePassword(_) => "Change Password",
        }
    }

    fn category(&self) -> NodeCategory {
        match self {
            ExecutorEnum::Start(_) => NodeCategory::Scan,
            ExecutorEnum::Base(_) => NodeCategory::Scan,
            ExecutorEnum::GetVertices(_) => NodeCategory::Scan,
            ExecutorEnum::GetNeighbors(_) => NodeCategory::Scan,
            ExecutorEnum::GetProp(_) => NodeCategory::Scan,
            ExecutorEnum::AllPaths(_) => NodeCategory::Path,
            ExecutorEnum::Expand(_) => NodeCategory::Traversal,
            ExecutorEnum::ExpandAll(_) => NodeCategory::Traversal,
            ExecutorEnum::Traverse(_) => NodeCategory::Traversal,
            ExecutorEnum::ShortestPath(_) => NodeCategory::Path,
            ExecutorEnum::MultiShortestPath(_) => NodeCategory::Path,
            ExecutorEnum::InnerJoin(_) => NodeCategory::Join,
            ExecutorEnum::HashInnerJoin(_) => NodeCategory::Join,
            ExecutorEnum::LeftJoin(_) => NodeCategory::Join,
            ExecutorEnum::HashLeftJoin(_) => NodeCategory::Join,
            ExecutorEnum::CrossJoin(_) => NodeCategory::Join,
            ExecutorEnum::Union(_) => NodeCategory::SetOp,
            ExecutorEnum::UnionAll(_) => NodeCategory::SetOp,
            ExecutorEnum::Minus(_) => NodeCategory::SetOp,
            ExecutorEnum::Intersect(_) => NodeCategory::SetOp,
            ExecutorEnum::Filter(_) => NodeCategory::Filter,
            ExecutorEnum::Project(_) => NodeCategory::Project,
            ExecutorEnum::Limit(_) => NodeCategory::Sort,
            ExecutorEnum::Sort(_) => NodeCategory::Sort,
            ExecutorEnum::TopN(_) => NodeCategory::Sort,
            ExecutorEnum::Sample(_) => NodeCategory::Other,
            ExecutorEnum::Aggregate(_) => NodeCategory::Aggregate,
            ExecutorEnum::GroupBy(_) => NodeCategory::Aggregate,
            ExecutorEnum::Having(_) => NodeCategory::Filter,
            ExecutorEnum::Dedup(_) => NodeCategory::Aggregate,
            ExecutorEnum::Unwind(_) => NodeCategory::DataCollect,
            ExecutorEnum::Assign(_) => NodeCategory::DataCollect,
            ExecutorEnum::AppendVertices(_) => NodeCategory::Traversal,
            ExecutorEnum::RollUpApply(_) => NodeCategory::DataCollect,
            ExecutorEnum::PatternApply(_) => NodeCategory::DataCollect,
            ExecutorEnum::Loop(_) => NodeCategory::Control,
            ExecutorEnum::ForLoop(_) => NodeCategory::Control,
            ExecutorEnum::WhileLoop(_) => NodeCategory::Control,
            ExecutorEnum::Select(_) => NodeCategory::Control,
            ExecutorEnum::ScanEdges(_) => NodeCategory::Scan,
            ExecutorEnum::ScanVertices(_) => NodeCategory::Scan,
            ExecutorEnum::IndexScan(_) => NodeCategory::Scan,
            ExecutorEnum::Argument(_) => NodeCategory::Control,
            ExecutorEnum::PassThrough(_) => NodeCategory::Control,
            ExecutorEnum::DataCollect(_) => NodeCategory::DataCollect,
            ExecutorEnum::BFSShortest(_) => NodeCategory::Path,
            ExecutorEnum::ShowSpaces(_) => NodeCategory::Admin,
            ExecutorEnum::ShowTags(_) => NodeCategory::Admin,
            ExecutorEnum::ShowEdges(_) => NodeCategory::Admin,
            ExecutorEnum::CreateTagIndex(_) => NodeCategory::Admin,
            ExecutorEnum::DropTagIndex(_) => NodeCategory::Admin,
            ExecutorEnum::DescTagIndex(_) => NodeCategory::Admin,
            ExecutorEnum::ShowTagIndexes(_) => NodeCategory::Admin,
            ExecutorEnum::RebuildTagIndex(_) => NodeCategory::Admin,
            ExecutorEnum::CreateEdgeIndex(_) => NodeCategory::Admin,
            ExecutorEnum::DropEdgeIndex(_) => NodeCategory::Admin,
            ExecutorEnum::DescEdgeIndex(_) => NodeCategory::Admin,
            ExecutorEnum::ShowEdgeIndexes(_) => NodeCategory::Admin,
            ExecutorEnum::RebuildEdgeIndex(_) => NodeCategory::Admin,
            ExecutorEnum::CreateSpace(_) => NodeCategory::Admin,
            ExecutorEnum::DropSpace(_) => NodeCategory::Admin,
            ExecutorEnum::DescSpace(_) => NodeCategory::Admin,
            ExecutorEnum::CreateTag(_) => NodeCategory::Admin,
            ExecutorEnum::AlterTag(_) => NodeCategory::Admin,
            ExecutorEnum::DescTag(_) => NodeCategory::Admin,
            ExecutorEnum::DropTag(_) => NodeCategory::Admin,
            ExecutorEnum::CreateEdge(_) => NodeCategory::Admin,
            ExecutorEnum::AlterEdge(_) => NodeCategory::Admin,
            ExecutorEnum::DescEdge(_) => NodeCategory::Admin,
            ExecutorEnum::DropEdge(_) => NodeCategory::Admin,
            ExecutorEnum::CreateUser(_) => NodeCategory::Admin,
            ExecutorEnum::AlterUser(_) => NodeCategory::Admin,
            ExecutorEnum::DropUser(_) => NodeCategory::Admin,
            ExecutorEnum::ChangePassword(_) => NodeCategory::Admin,
        }
    }
}
