// Proto module - only compiled when "service" feature is enabled
#![cfg(feature = "service")]

// Include generated proto code
// The proto file is generated by build.rs during compilation
// Note: tonic-build generates "inversearch.rs", not "inversearch.proto.rs"
include!(concat!(env!("OUT_DIR"), "/inversearch.rs"));
